In [1]:
# Read the annotations file
import pandas as pd
df_all = pd.read_csv('../data/raw-data/slice_annotation.csv', index_col = 0)

print(df_all.shape)
(df_all.head())

(390, 5)

,patient_id,C3_Manual_slice,Datatype,Z_spacing,XY_spacing
0,mdacc_HNSCC-01-0216_CT-SIM-08-10-2008-_raw_raw...,192,val,NaN,NaN
0,mdacc_HNSCC-01-0217_CT-SIM-12-16-2012-_raw_raw...,131,train,NaN,NaN
0,mdacc_HNSCC-01-0218_CT-SIM-09-13-2009-_raw_raw...,166,train,NaN,NaN
0,mdacc_HNSCC-01-0219_CT-SIM-09-13-2009-_raw_raw...,150,train,NaN,NaN
0,mdacc_HNSCC-01-0220_CT-SIM-11-13-2011-_raw_raw...,129,train,NaN,NaN

In [2]:
# Apply window utility - used mainly in selection training data prep
def apply_window(image, win_centre= 40, win_width= 400):
    range_bottom = win_centre - win_width / 2
    scale = 256 / win_width
    image = image - range_bottom

    image = image * scale
    image[image < 0] = 0
    image[image > 255] = 255

    return image

In [4]:
#### Slice prediction model data preparation - TRAINING
# The z-offset for a slice should represent its offset above or below the C3 slice in mm 
# Slices below the chosen C3 slice should be given negative offsets.
import matplotlib.pyplot as plt
import functools
from skimage.transform import resize
import SimpleITK as sitk
import numpy as np

df_to_be_writen = pd.DataFrame()
df_train = df_all[df_all.Datatype.isin(['train'])]
image_dir = '../data/raw-data/scans/'
targ_dir = '../data/train/train_prediction/predcition_npy/train/'
csv_write_path = '../data/train/train_selection/prediction_meta/train.csv'
j = 0
for idx in range(df_train.shape[0]):
    image_path = image_dir + df_train.iloc[idx,0]+'.nrrd'
    patient_id =df_train.iloc[idx,0][:37]
    c3_slice = df_train.iloc[idx,1]
    print(patient_id,image_path,c3_slice,targ_dir)
     
    image_sitk =  sitk.ReadImage(image_path)
    image_array  = sitk.GetArrayFromImage(image_sitk)
    spacing =  image_sitk.GetSpacing()[2]
    
    image_array = apply_window(image_array)
    windowed_images = image_array

    print(idx+1,'th',patient_id ,image_array.shape,np.max(image_array),spacing)

    resize_func = functools.partial(resize, output_shape=[256,256],
                                    preserve_range=True, anti_aliasing=True, mode='constant')
    series = np.dstack([resize_func(im) for im in windowed_images])
    series = np.transpose(series[:, :, :, np.newaxis], [2, 0, 1, 3])
#     print(type(series),series.shape)
    for slice_idx in range(image_array.shape[0]):
        offset = spacing*(slice_idx-c3_slice)
        offset = round(offset,5)
        npy_name = str(j).zfill(6)+'_'+patient_id+'.npy'
        npy_path = targ_dir +npy_name
        im_array = series[slice_idx,:,:,:].astype(np.uint8)
        np.save(npy_path,im_array)
#         print(npy_path ,im_array.shape,'spacing',spacing)

        df_offset = pd.DataFrame({'NPY_name':npy_name,
                       'ZOffset':offset},index=[0])
        #df_to_be_writen = df_to_be_writen.append(df_offset)
        df_to_be_writen = pd.concat([df_to_be_writen,df_offset])
        df_to_be_writen.to_csv(csv_write_path)   
        j=j+1
    print()

mdacc_HNSCC-01-0217_CT-SIM-12-16-2012 ../data/raw-data/scans/mdacc_HNSCC-01-0217_CT-SIM-12-16-2012-_raw_raw_raw_xx.nrrd 131 ../data/train/train_selection/selection_npy/train/
1 th mdacc_HNSCC-01-0217_CT-SIM-12-16-2012 (260, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0218_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0218_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 166 ../data/train/train_selection/selection_npy/train/
2 th mdacc_HNSCC-01-0218_CT-SIM-09-13-2009 (294, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0219_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0219_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 150 ../data/train/train_selection/selection_npy/train/
3 th mdacc_HNSCC-01-0219_CT-SIM-09-13-2009 (240, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0220_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0220_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 129 ../data/train/train_selection/selection_npy/train/
4 th mdacc_HNSCC-01-0220_CT-SIM-11-13-2011 (343, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0222_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0222_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 175 ../data/train/train_selection/selection_npy/train/
5 th mdacc_HNSCC-01-0222_CT-SIM-09-13-2009 (268, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0223_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0223_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 184 ../data/train/train_selection/selection_npy/train/
6 th mdacc_HNSCC-01-0223_CT-SIM-10-10-2010 (312, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0224_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0224_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 132 ../data/train/train_selection/selection_npy/train/
7 th mdacc_HNSCC-01-0224_CT-SIM-07-08-2007 (213, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0230_CT-SIM-05-08-2005 ../data/raw-data/scans/mdacc_HNSCC-01-0230_CT-SIM-05-08-2005-_raw_raw_raw_xx.nrrd 48 ../data/train/train_selection/selection_npy/train/
8 th mdacc_HNSCC-01-0230_CT-SIM-05-08-2005 (86, 512, 512) 255.0 3.0

mdacc_HNSCC-01-0232_CT-SIM-05-08-2005 ../data/raw-data/scans/mdacc_HNSCC-01-0232_CT-SIM-05-08-2005-_raw_raw_raw_xx.nrrd 155 ../data/train/train_selection/selection_npy/train/
9 th mdacc_HNSCC-01-0232_CT-SIM-05-08-2005 (269, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0233_CT-SIM-05-08-2005 ../data/raw-data/scans/mdacc_HNSCC-01-0233_CT-SIM-05-08-2005-_raw_raw_raw_xx.nrrd 158 ../data/train/train_selection/selection_npy/train/
10 th mdacc_HNSCC-01-0233_CT-SIM-05-08-2005 (231, 512, 512) 255.0 1.0000000000000284

mdacc_HNSCC-01-0234_CT-SIM-05-08-2005 ../data/raw-data/scans/mdacc_HNSCC-01-0234_CT-SIM-05-08-2005-_raw_raw_raw_xx.nrrd 163 ../data/train/train_selection/selection_npy/train/
11 th mdacc_HNSCC-01-0234_CT-SIM-05-08-2005 (261, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0235_CT-SIM-05-08-2005 ../data/raw-data/scans/mdacc_HNSCC-01-0235_CT-SIM-05-08-2005-_raw_raw_raw_xx.nrrd 160 ../data/train/train_selection/selection_npy/train/
12 th mdacc_HNSCC-01-0235_CT-SIM-05-08-2005 (265, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0237_CT-SIM-05-08-2005 ../data/raw-data/scans/mdacc_HNSCC-01-0237_CT-SIM-05-08-2005-_raw_raw_raw_xx.nrrd 49 ../data/train/train_selection/selection_npy/train/
13 th mdacc_HNSCC-01-0237_CT-SIM-05-08-2005 (90, 512, 512) 255.0 3.0

mdacc_HNSCC-01-0238_CT-SIM-05-08-2005 ../data/raw-data/scans/mdacc_HNSCC-01-0238_CT-SIM-05-08-2005-_raw_raw_raw_xx.nrrd 170 ../data/train/train_selection/selection_npy/train/
14 th mdacc_HNSCC-01-0238_CT-SIM-05-08-2005 (261, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0239_CT-SIM-05-08-2005 ../data/raw-data/scans/mdacc_HNSCC-01-0239_CT-SIM-05-08-2005-_raw_raw_raw_xx.nrrd 46 ../data/train/train_selection/selection_npy/train/
15 th mdacc_HNSCC-01-0239_CT-SIM-05-08-2005 (84, 512, 512) 255.0 3.0

mdacc_HNSCC-01-0240_CT-SIM-05-08-2005 ../data/raw-data/scans/mdacc_HNSCC-01-0240_CT-SIM-05-08-2005-_raw_raw_raw_xx.nrrd 194 ../data/train/train_selection/selection_npy/train/
16 th mdacc_HNSCC-01-0240_CT-SIM-05-08-2005 (300, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0242_CT-SIM-05-08-2005 ../data/raw-data/scans/mdacc_HNSCC-01-0242_CT-SIM-05-08-2005-_raw_raw_raw_xx.nrrd 158 ../data/train/train_selection/selection_npy/train/
17 th mdacc_HNSCC-01-0242_CT-SIM-05-08-2005 (279, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0243_CT-SIM-05-08-2005 ../data/raw-data/scans/mdacc_HNSCC-01-0243_CT-SIM-05-08-2005-_raw_raw_raw_xx.nrrd 159 ../data/train/train_selection/selection_npy/train/
18 th mdacc_HNSCC-01-0243_CT-SIM-05-08-2005 (244, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0244_CT-SIM-05-08-2005 ../data/raw-data/scans/mdacc_HNSCC-01-0244_CT-SIM-05-08-2005-_raw_raw_raw_xx.nrrd 165 ../data/train/train_selection/selection_npy/train/
19 th mdacc_HNSCC-01-0244_CT-SIM-05-08-2005 (265, 512, 512) 255.0 0.9999999999999716

mdacc_HNSCC-01-0245_CT-SIM-05-08-2005 ../data/raw-data/scans/mdacc_HNSCC-01-0245_CT-SIM-05-08-2005-_raw_raw_raw_xx.nrrd 148 ../data/train/train_selection/selection_npy/train/
20 th mdacc_HNSCC-01-0245_CT-SIM-05-08-2005 (250, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0247_CT-SIM-05-08-2005 ../data/raw-data/scans/mdacc_HNSCC-01-0247_CT-SIM-05-08-2005-_raw_raw_raw_xx.nrrd 62 ../data/train/train_selection/selection_npy/train/
21 th mdacc_HNSCC-01-0247_CT-SIM-05-08-2005 (102, 512, 512) 255.0 3.0

mdacc_HNSCC-01-0248_CT-SIM-05-08-2005 ../data/raw-data/scans/mdacc_HNSCC-01-0248_CT-SIM-05-08-2005-_raw_raw_raw_xx.nrrd 164 ../data/train/train_selection/selection_npy/train/
22 th mdacc_HNSCC-01-0248_CT-SIM-05-08-2005 (265, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0249_CT-SIM-05-08-2005 ../data/raw-data/scans/mdacc_HNSCC-01-0249_CT-SIM-05-08-2005-_raw_raw_raw_xx.nrrd 150 ../data/train/train_selection/selection_npy/train/
23 th mdacc_HNSCC-01-0249_CT-SIM-05-08-2005 (248, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0250_CT-SIM-05-08-2005 ../data/raw-data/scans/mdacc_HNSCC-01-0250_CT-SIM-05-08-2005-_raw_raw_raw_xx.nrrd 140 ../data/train/train_selection/selection_npy/train/
24 th mdacc_HNSCC-01-0250_CT-SIM-05-08-2005 (237, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0252_CT-SIM-05-08-2005 ../data/raw-data/scans/mdacc_HNSCC-01-0252_CT-SIM-05-08-2005-_raw_raw_raw_xx.nrrd 175 ../data/train/train_selection/selection_npy/train/
25 th mdacc_HNSCC-01-0252_CT-SIM-05-08-2005 (251, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0253_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0253_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 184 ../data/train/train_selection/selection_npy/train/
26 th mdacc_HNSCC-01-0253_CT-SIM-06-11-2006 (279, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0254_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0254_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 163 ../data/train/train_selection/selection_npy/train/
27 th mdacc_HNSCC-01-0254_CT-SIM-06-11-2006 (264, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0255_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0255_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 152 ../data/train/train_selection/selection_npy/train/
28 th mdacc_HNSCC-01-0255_CT-SIM-06-11-2006 (222, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0257_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0257_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 179 ../data/train/train_selection/selection_npy/train/
29 th mdacc_HNSCC-01-0257_CT-SIM-06-11-2006 (280, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0258_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0258_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 165 ../data/train/train_selection/selection_npy/train/
30 th mdacc_HNSCC-01-0258_CT-SIM-06-11-2006 (251, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0259_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0259_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 155 ../data/train/train_selection/selection_npy/train/
31 th mdacc_HNSCC-01-0259_CT-SIM-06-11-2006 (260, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0260_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0260_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 33 ../data/train/train_selection/selection_npy/train/
32 th mdacc_HNSCC-01-0260_CT-SIM-06-11-2006 (67, 512, 512) 255.0 3.0

mdacc_HNSCC-01-0262_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0262_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 152 ../data/train/train_selection/selection_npy/train/
33 th mdacc_HNSCC-01-0262_CT-SIM-06-11-2006 (253, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0263_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0263_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 153 ../data/train/train_selection/selection_npy/train/

34 th mdacc_HNSCC-01-0263_CT-SIM-06-11-2006 (251, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0264_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0264_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 142 ../data/train/train_selection/selection_npy/train/
35 th mdacc_HNSCC-01-0264_CT-SIM-06-11-2006 (254, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0265_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0265_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 153 ../data/train/train_selection/selection_npy/train/
36 th mdacc_HNSCC-01-0265_CT-SIM-06-11-2006 (250, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0267_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0267_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 145 ../data/train/train_selection/selection_npy/train/
37 th mdacc_HNSCC-01-0267_CT-SIM-06-11-2006 (270, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0268_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0268_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 38 ../data/train/train_selection/selection_npy/train/
38 th mdacc_HNSCC-01-0268_CT-SIM-06-11-2006 (58, 512, 512) 255.0 3.75

mdacc_HNSCC-01-0269_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0269_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 157 ../data/train/train_selection/selection_npy/train/
39 th mdacc_HNSCC-01-0269_CT-SIM-06-11-2006 (262, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0271_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0271_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 170 ../data/train/train_selection/selection_npy/train/
40 th mdacc_HNSCC-01-0271_CT-SIM-06-11-2006 (275, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0273_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0273_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 28 ../data/train/train_selection/selection_npy/train/
41 th mdacc_HNSCC-01-0273_CT-SIM-06-11-2006 (43, 512, 512) 255.0 5.0

mdacc_HNSCC-01-0274_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0274_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 168 ../data/train/train_selection/selection_npy/train/
42 th mdacc_HNSCC-01-0274_CT-SIM-06-11-2006 (268, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0275_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0275_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 198 ../data/train/train_selection/selection_npy/train/
43 th mdacc_HNSCC-01-0275_CT-SIM-06-11-2006 (313, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0276_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0276_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 172 ../data/train/train_selection/selection_npy/train/
44 th mdacc_HNSCC-01-0276_CT-SIM-06-11-2006 (294, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0278_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0278_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 178 ../data/train/train_selection/selection_npy/train/
45 th mdacc_HNSCC-01-0278_CT-SIM-06-11-2006 (268, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0281_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0281_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 152 ../data/train/train_selection/selection_npy/train/
46 th mdacc_HNSCC-01-0281_CT-SIM-08-10-2008 (250, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0282_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0282_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 50 ../data/train/train_selection/selection_npy/train/
47 th mdacc_HNSCC-01-0282_CT-SIM-06-11-2006 (80, 512, 512) 255.0 2.5

mdacc_HNSCC-01-0283_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0283_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 144 ../data/train/train_selection/selection_npy/train/
48 th mdacc_HNSCC-01-0283_CT-SIM-06-11-2006 (228, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0285_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0285_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 155 ../data/train/train_selection/selection_npy/train/
49 th mdacc_HNSCC-01-0285_CT-SIM-06-11-2006 (243, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0286_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0286_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 171 ../data/train/train_selection/selection_npy/train/
50 th mdacc_HNSCC-01-0286_CT-SIM-06-11-2006 (314, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0287_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0287_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 184 ../data/train/train_selection/selection_npy/train/
51 th mdacc_HNSCC-01-0287_CT-SIM-07-08-2007 (288, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0288_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0288_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 135 ../data/train/train_selection/selection_npy/train/
52 th mdacc_HNSCC-01-0288_CT-SIM-07-08-2007 (242, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0290_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0290_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 145 ../data/train/train_selection/selection_npy/train/
53 th mdacc_HNSCC-01-0290_CT-SIM-07-08-2007 (260, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0291_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0291_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 155 ../data/train/train_selection/selection_npy/train/
54 th mdacc_HNSCC-01-0291_CT-SIM-07-08-2007 (263, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0292_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0292_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 142 ../data/train/train_selection/selection_npy/train/
55 th mdacc_HNSCC-01-0292_CT-SIM-07-08-2007 (237, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0293_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0293_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 154 ../data/train/train_selection/selection_npy/train/
56 th mdacc_HNSCC-01-0293_CT-SIM-07-08-2007 (266, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0296_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0296_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 164 ../data/train/train_selection/selection_npy/train/
57 th mdacc_HNSCC-01-0296_CT-SIM-07-08-2007 (261, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0297_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0297_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 158 ../data/train/train_selection/selection_npy/train/
58 th mdacc_HNSCC-01-0297_CT-SIM-07-08-2007 (254, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0299_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0299_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 163 ../data/train/train_selection/selection_npy/train/
59 th mdacc_HNSCC-01-0299_CT-SIM-07-08-2007 (265, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0300_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0300_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 164 ../data/train/train_selection/selection_npy/train/
60 th mdacc_HNSCC-01-0300_CT-SIM-07-08-2007 (255, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0302_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0302_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 182 ../data/train/train_selection/selection_npy/train/
61 th mdacc_HNSCC-01-0302_CT-SIM-07-08-2007 (294, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0303_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0303_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 193 ../data/train/train_selection/selection_npy/train/
62 th mdacc_HNSCC-01-0303_CT-SIM-07-08-2007 (290, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0304_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0304_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 142 ../data/train/train_selection/selection_npy/train/
63 th mdacc_HNSCC-01-0304_CT-SIM-07-08-2007 (241, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0305_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0305_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 154 ../data/train/train_selection/selection_npy/train/
64 th mdacc_HNSCC-01-0305_CT-SIM-07-08-2007 (259, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0307_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0307_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 164 ../data/train/train_selection/selection_npy/train/
65 th mdacc_HNSCC-01-0307_CT-SIM-07-08-2007 (269, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0308_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0308_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 144 ../data/train/train_selection/selection_npy/train/
66 th mdacc_HNSCC-01-0308_CT-SIM-07-08-2007 (239, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0309_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0309_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 64 ../data/train/train_selection/selection_npy/train/
67 th mdacc_HNSCC-01-0309_CT-SIM-07-08-2007 (141, 512, 512) 255.0 3.0

mdacc_HNSCC-01-0310_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0310_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 166 ../data/train/train_selection/selection_npy/train/

68 th mdacc_HNSCC-01-0310_CT-SIM-07-08-2007 (292, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0311_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0311_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 169 ../data/train/train_selection/selection_npy/train/
69 th mdacc_HNSCC-01-0311_CT-SIM-07-08-2007 (256, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0313_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0313_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 117 ../data/train/train_selection/selection_npy/train/
70 th mdacc_HNSCC-01-0313_CT-SIM-07-08-2007 (248, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0314_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0314_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 213 ../data/train/train_selection/selection_npy/train/
71 th mdacc_HNSCC-01-0314_CT-SIM-07-08-2007 (338, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0315_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0315_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 141 ../data/train/train_selection/selection_npy/train/
72 th mdacc_HNSCC-01-0315_CT-SIM-07-08-2007 (242, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0316_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0316_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 161 ../data/train/train_selection/selection_npy/train/
73 th mdacc_HNSCC-01-0316_CT-SIM-07-08-2007 (276, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0318_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0318_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 174 ../data/train/train_selection/selection_npy/train/
74 th mdacc_HNSCC-01-0318_CT-SIM-07-08-2007 (261, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0319_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0319_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 23 ../data/train/train_selection/selection_npy/train/
75 th mdacc_HNSCC-01-0319_CT-SIM-07-08-2007 (43, 512, 512) 255.0 5.0

mdacc_HNSCC-01-0320_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0320_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 52 ../data/train/train_selection/selection_npy/train/
76 th mdacc_HNSCC-01-0320_CT-SIM-07-08-2007 (87, 512, 512) 255.0 3.0

mdacc_HNSCC-01-0321_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0321_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 188 ../data/train/train_selection/selection_npy/train/
77 th mdacc_HNSCC-01-0321_CT-SIM-07-08-2007 (290, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0323_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0323_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 144 ../data/train/train_selection/selection_npy/train/
78 th mdacc_HNSCC-01-0323_CT-SIM-07-08-2007 (236, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0324_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0324_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 142 ../data/train/train_selection/selection_npy/train/
79 th mdacc_HNSCC-01-0324_CT-SIM-07-08-2007 (233, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0325_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0325_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 150 ../data/train/train_selection/selection_npy/train/
80 th mdacc_HNSCC-01-0325_CT-SIM-07-08-2007 (251, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0326_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0326_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 156 ../data/train/train_selection/selection_npy/train/
81 th mdacc_HNSCC-01-0326_CT-SIM-07-08-2007 (274, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0328_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0328_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 196 ../data/train/train_selection/selection_npy/train/
82 th mdacc_HNSCC-01-0328_CT-SIM-07-08-2007 (289, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0329_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0329_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 196 ../data/train/train_selection/selection_npy/train/
83 th mdacc_HNSCC-01-0329_CT-SIM-08-10-2008 (291, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0330_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0330_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 175 ../data/train/train_selection/selection_npy/train/
84 th mdacc_HNSCC-01-0330_CT-SIM-08-10-2008 (273, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0331_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0331_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 145 ../data/train/train_selection/selection_npy/train/
85 th mdacc_HNSCC-01-0331_CT-SIM-08-10-2008 (247, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0333_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0333_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 147 ../data/train/train_selection/selection_npy/train/
86 th mdacc_HNSCC-01-0333_CT-SIM-08-10-2008 (252, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0334_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0334_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 169 ../data/train/train_selection/selection_npy/train/
87 th mdacc_HNSCC-01-0334_CT-SIM-08-10-2008 (272, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0335_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0335_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 151 ../data/train/train_selection/selection_npy/train/
88 th mdacc_HNSCC-01-0335_CT-SIM-08-10-2008 (263, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0336_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0336_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 142 ../data/train/train_selection/selection_npy/train/
89 th mdacc_HNSCC-01-0336_CT-SIM-08-10-2008 (269, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0338_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0338_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 157 ../data/train/train_selection/selection_npy/train/
90 th mdacc_HNSCC-01-0338_CT-SIM-08-10-2008 (375, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0339_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0339_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 139 ../data/train/train_selection/selection_npy/train/
91 th mdacc_HNSCC-01-0339_CT-SIM-08-10-2008 (235, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0340_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0340_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 170 ../data/train/train_selection/selection_npy/train/
92 th mdacc_HNSCC-01-0340_CT-SIM-08-10-2008 (268, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0341_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0341_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 157 ../data/train/train_selection/selection_npy/train/
93 th mdacc_HNSCC-01-0341_CT-SIM-08-10-2008 (273, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0342_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0342_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 151 ../data/train/train_selection/selection_npy/train/
94 th mdacc_HNSCC-01-0342_CT-SIM-08-10-2008 (232, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0344_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0344_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 166 ../data/train/train_selection/selection_npy/train/
95 th mdacc_HNSCC-01-0344_CT-SIM-08-10-2008 (267, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0345_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0345_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 170 ../data/train/train_selection/selection_npy/train/
96 th mdacc_HNSCC-01-0345_CT-SIM-08-10-2008 (272, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0346_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0346_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 152 ../data/train/train_selection/selection_npy/train/
97 th mdacc_HNSCC-01-0346_CT-SIM-08-10-2008 (350, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0347_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0347_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 138 ../data/train/train_selection/selection_npy/train/
98 th mdacc_HNSCC-01-0347_CT-SIM-08-10-2008 (240, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0349_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0349_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 153 ../data/train/train_selection/selection_npy/train/
99 th mdacc_HNSCC-01-0349_CT-SIM-08-10-2008 (253, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0350_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0350_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 181 ../data/train/train_selection/selection_npy/train/
100 th mdacc_HNSCC-01-0350_CT-SIM-08-10-2008 (298, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0351_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0351_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 137 ../data/train/train_selection/selection_npy/train/
101 th mdacc_HNSCC-01-0351_CT-SIM-08-10-2008 (237, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0352_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0352_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 175 ../data/train/train_selection/selection_npy/train/

102 th mdacc_HNSCC-01-0352_CT-SIM-08-10-2008 (287, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0355_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0355_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 142 ../data/train/train_selection/selection_npy/train/
103 th mdacc_HNSCC-01-0355_CT-SIM-08-10-2008 (250, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0356_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0356_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 147 ../data/train/train_selection/selection_npy/train/
104 th mdacc_HNSCC-01-0356_CT-SIM-08-10-2008 (273, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0357_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0357_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 158 ../data/train/train_selection/selection_npy/train/
105 th mdacc_HNSCC-01-0357_CT-SIM-08-10-2008 (359, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0358_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0358_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 155 ../data/train/train_selection/selection_npy/train/
106 th mdacc_HNSCC-01-0358_CT-SIM-08-10-2008 (291, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0360_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0360_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 141 ../data/train/train_selection/selection_npy/train/
107 th mdacc_HNSCC-01-0360_CT-SIM-08-10-2008 (228, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0361_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0361_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 46 ../data/train/train_selection/selection_npy/train/
108 th mdacc_HNSCC-01-0361_CT-SIM-08-10-2008 (89, 512, 512) 255.0 3.0

mdacc_HNSCC-01-0362_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0362_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 165 ../data/train/train_selection/selection_npy/train/
109 th mdacc_HNSCC-01-0362_CT-SIM-08-10-2008 (283, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0363_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0363_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 165 ../data/train/train_selection/selection_npy/train/
110 th mdacc_HNSCC-01-0363_CT-SIM-08-10-2008 (258, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0365_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0365_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 150 ../data/train/train_selection/selection_npy/train/
111 th mdacc_HNSCC-01-0365_CT-SIM-08-10-2008 (280, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0366_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0366_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 170 ../data/train/train_selection/selection_npy/train/
112 th mdacc_HNSCC-01-0366_CT-SIM-08-10-2008 (278, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0367_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0367_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 163 ../data/train/train_selection/selection_npy/train/
113 th mdacc_HNSCC-01-0367_CT-SIM-08-10-2008 (280, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0368_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0368_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 135 ../data/train/train_selection/selection_npy/train/
114 th mdacc_HNSCC-01-0368_CT-SIM-08-10-2008 (229, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0370_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0370_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 159 ../data/train/train_selection/selection_npy/train/
115 th mdacc_HNSCC-01-0370_CT-SIM-08-10-2008 (259, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0371_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0371_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 139 ../data/train/train_selection/selection_npy/train/
116 th mdacc_HNSCC-01-0371_CT-SIM-08-10-2008 (229, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0372_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0372_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 164 ../data/train/train_selection/selection_npy/train/
117 th mdacc_HNSCC-01-0372_CT-SIM-08-10-2008 (251, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0373_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0373_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 173 ../data/train/train_selection/selection_npy/train/
118 th mdacc_HNSCC-01-0373_CT-SIM-08-10-2008 (303, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0375_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0375_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 144 ../data/train/train_selection/selection_npy/train/
119 th mdacc_HNSCC-01-0375_CT-SIM-08-10-2008 (363, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0376_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0376_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 147 ../data/train/train_selection/selection_npy/train/
120 th mdacc_HNSCC-01-0376_CT-SIM-08-10-2008 (372, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0377_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0377_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 155 ../data/train/train_selection/selection_npy/train/
121 th mdacc_HNSCC-01-0377_CT-SIM-08-10-2008 (241, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0378_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0378_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 178 ../data/train/train_selection/selection_npy/train/
122 th mdacc_HNSCC-01-0378_CT-SIM-08-10-2008 (280, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0380_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0380_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 170 ../data/train/train_selection/selection_npy/train/
123 th mdacc_HNSCC-01-0380_CT-SIM-08-10-2008 (268, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0381_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0381_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 125 ../data/train/train_selection/selection_npy/train/
124 th mdacc_HNSCC-01-0381_CT-SIM-08-10-2008 (204, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0382_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0382_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 165 ../data/train/train_selection/selection_npy/train/
125 th mdacc_HNSCC-01-0382_CT-SIM-08-10-2008 (271, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0383_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0383_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 166 ../data/train/train_selection/selection_npy/train/
126 th mdacc_HNSCC-01-0383_CT-SIM-08-10-2008 (275, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0385_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0385_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 166 ../data/train/train_selection/selection_npy/train/
127 th mdacc_HNSCC-01-0385_CT-SIM-08-10-2008 (312, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0386_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0386_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 171 ../data/train/train_selection/selection_npy/train/
128 th mdacc_HNSCC-01-0386_CT-SIM-08-10-2008 (273, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0387_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0387_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 162 ../data/train/train_selection/selection_npy/train/
129 th mdacc_HNSCC-01-0387_CT-SIM-08-10-2008 (368, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0388_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0388_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 50 ../data/train/train_selection/selection_npy/train/
130 th mdacc_HNSCC-01-0388_CT-SIM-08-10-2008 (105, 512, 512) 255.0 3.0

mdacc_HNSCC-01-0390_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0390_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 165 ../data/train/train_selection/selection_npy/train/
131 th mdacc_HNSCC-01-0390_CT-SIM-08-10-2008 (252, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0391_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0391_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 173 ../data/train/train_selection/selection_npy/train/
132 th mdacc_HNSCC-01-0391_CT-SIM-08-10-2008 (263, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0392_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0392_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 137 ../data/train/train_selection/selection_npy/train/
133 th mdacc_HNSCC-01-0392_CT-SIM-08-10-2008 (242, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0393_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0393_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 189 ../data/train/train_selection/selection_npy/train/
134 th mdacc_HNSCC-01-0393_CT-SIM-08-10-2008 (281, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0395_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0395_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 178 ../data/train/train_selection/selection_npy/train/
135 th mdacc_HNSCC-01-0395_CT-SIM-08-10-2008 (269, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0396_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0396_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 149 ../data/train/train_selection/selection_npy/train/
136 th mdacc_HNSCC-01-0396_CT-SIM-09-13-2009 (276, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0397_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0397_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 161 ../data/train/train_selection/selection_npy/train/
137 th mdacc_HNSCC-01-0397_CT-SIM-09-13-2009 (248, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0398_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0398_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 144 ../data/train/train_selection/selection_npy/train/
138 th mdacc_HNSCC-01-0398_CT-SIM-09-13-2009 (243, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0400_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0400_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 145 ../data/train/train_selection/selection_npy/train/
139 th mdacc_HNSCC-01-0400_CT-SIM-09-13-2009 (352, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0401_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0401_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 154 ../data/train/train_selection/selection_npy/train/
140 th mdacc_HNSCC-01-0401_CT-SIM-09-13-2009 (253, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0402_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0402_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 131 ../data/train/train_selection/selection_npy/train/
141 th mdacc_HNSCC-01-0402_CT-SIM-11-13-2011 (276, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0403_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0403_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 163 ../data/train/train_selection/selection_npy/train/
142 th mdacc_HNSCC-01-0403_CT-SIM-09-13-2009 (263, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0405_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0405_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 142 ../data/train/train_selection/selection_npy/train/
143 th mdacc_HNSCC-01-0405_CT-SIM-09-13-2009 (237, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0406_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0406_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 144 ../data/train/train_selection/selection_npy/train/
144 th mdacc_HNSCC-01-0406_CT-SIM-09-13-2009 (240, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0407_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0407_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 163 ../data/train/train_selection/selection_npy/train/
145 th mdacc_HNSCC-01-0407_CT-SIM-09-13-2009 (266, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0408_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0408_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 161 ../data/train/train_selection/selection_npy/train/
146 th mdacc_HNSCC-01-0408_CT-SIM-09-13-2009 (274, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0410_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0410_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 167 ../data/train/train_selection/selection_npy/train/
147 th mdacc_HNSCC-01-0410_CT-SIM-09-13-2009 (280, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0411_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0411_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 150 ../data/train/train_selection/selection_npy/train/
148 th mdacc_HNSCC-01-0411_CT-SIM-09-13-2009 (268, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0412_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0412_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 182 ../data/train/train_selection/selection_npy/train/
149 th mdacc_HNSCC-01-0412_CT-SIM-09-13-2009 (272, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0413_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0413_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 153 ../data/train/train_selection/selection_npy/train/
150 th mdacc_HNSCC-01-0413_CT-SIM-09-13-2009 (354, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0415_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0415_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 150 ../data/train/train_selection/selection_npy/train/
151 th mdacc_HNSCC-01-0415_CT-SIM-09-13-2009 (239, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0416_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0416_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 186 ../data/train/train_selection/selection_npy/train/
152 th mdacc_HNSCC-01-0416_CT-SIM-09-13-2009 (329, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0417_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0417_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 156 ../data/train/train_selection/selection_npy/train/
153 th mdacc_HNSCC-01-0417_CT-SIM-09-13-2009 (366, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0418_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0418_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 150 ../data/train/train_selection/selection_npy/train/
154 th mdacc_HNSCC-01-0418_CT-SIM-09-13-2009 (270, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0420_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0420_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 161 ../data/train/train_selection/selection_npy/train/
155 th mdacc_HNSCC-01-0420_CT-SIM-09-13-2009 (282, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0421_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0421_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 178 ../data/train/train_selection/selection_npy/train/
156 th mdacc_HNSCC-01-0421_CT-SIM-09-13-2009 (286, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0422_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0422_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 143 ../data/train/train_selection/selection_npy/train/
157 th mdacc_HNSCC-01-0422_CT-SIM-09-13-2009 (244, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0423_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0423_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 159 ../data/train/train_selection/selection_npy/train/
158 th mdacc_HNSCC-01-0423_CT-SIM-09-13-2009 (262, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0425_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0425_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 133 ../data/train/train_selection/selection_npy/train/
159 th mdacc_HNSCC-01-0425_CT-SIM-09-13-2009 (229, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0426_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0426_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 151 ../data/train/train_selection/selection_npy/train/
160 th mdacc_HNSCC-01-0426_CT-SIM-09-13-2009 (251, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0427_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0427_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 55 ../data/train/train_selection/selection_npy/train/
161 th mdacc_HNSCC-01-0427_CT-SIM-09-13-2009 (100, 512, 512) 255.0 3.0

mdacc_HNSCC-01-0428_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0428_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 174 ../data/train/train_selection/selection_npy/train/
162 th mdacc_HNSCC-01-0428_CT-SIM-09-13-2009 (280, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0430_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0430_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 176 ../data/train/train_selection/selection_npy/train/
163 th mdacc_HNSCC-01-0430_CT-SIM-09-13-2009 (282, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0431_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0431_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 195 ../data/train/train_selection/selection_npy/train/
164 th mdacc_HNSCC-01-0431_CT-SIM-09-13-2009 (415, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0432_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0432_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 152 ../data/train/train_selection/selection_npy/train/
165 th mdacc_HNSCC-01-0432_CT-SIM-09-13-2009 (257, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0433_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0433_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 147 ../data/train/train_selection/selection_npy/train/
166 th mdacc_HNSCC-01-0433_CT-SIM-09-13-2009 (269, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0436_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0436_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 148 ../data/train/train_selection/selection_npy/train/
167 th mdacc_HNSCC-01-0436_CT-SIM-09-13-2009 (300, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0437_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0437_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 40 ../data/train/train_selection/selection_npy/train/
168 th mdacc_HNSCC-01-0437_CT-SIM-09-13-2009 (71, 512, 512) 255.0 3.0

mdacc_HNSCC-01-0438_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0438_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 153 ../data/train/train_selection/selection_npy/train/

169 th mdacc_HNSCC-01-0438_CT-SIM-09-13-2009 (282, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0439_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0439_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 148 ../data/train/train_selection/selection_npy/train/
170 th mdacc_HNSCC-01-0439_CT-SIM-09-13-2009 (356, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0441_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0441_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 210 ../data/train/train_selection/selection_npy/train/
171 th mdacc_HNSCC-01-0441_CT-SIM-09-13-2009 (361, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0442_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0442_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 145 ../data/train/train_selection/selection_npy/train/
172 th mdacc_HNSCC-01-0442_CT-SIM-09-13-2009 (243, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0443_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0443_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 182 ../data/train/train_selection/selection_npy/train/
173 th mdacc_HNSCC-01-0443_CT-SIM-08-10-2008 (327, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0444_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0444_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 181 ../data/train/train_selection/selection_npy/train/
174 th mdacc_HNSCC-01-0444_CT-SIM-09-13-2009 (320, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0446_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0446_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 77 ../data/train/train_selection/selection_npy/train/
175 th mdacc_HNSCC-01-0446_CT-SIM-09-13-2009 (124, 512, 512) 255.0 2.5

mdacc_HNSCC-01-0447_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0447_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 170 ../data/train/train_selection/selection_npy/train/
176 th mdacc_HNSCC-01-0447_CT-SIM-09-13-2009 (306, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0448_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0448_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 155 ../data/train/train_selection/selection_npy/train/
177 th mdacc_HNSCC-01-0448_CT-SIM-09-13-2009 (296, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0449_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0449_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 188 ../data/train/train_selection/selection_npy/train/
178 th mdacc_HNSCC-01-0449_CT-SIM-09-13-2009 (300, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0451_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0451_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 81 ../data/train/train_selection/selection_npy/train/
179 th mdacc_HNSCC-01-0451_CT-SIM-09-13-2009 (132, 512, 512) 255.0 2.0

mdacc_HNSCC-01-0452_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0452_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 146 ../data/train/train_selection/selection_npy/train/
180 th mdacc_HNSCC-01-0452_CT-SIM-09-13-2009 (292, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0453_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0453_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 106 ../data/train/train_selection/selection_npy/train/
181 th mdacc_HNSCC-01-0453_CT-SIM-09-13-2009 (228, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0454_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0454_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 147 ../data/train/train_selection/selection_npy/train/
182 th mdacc_HNSCC-01-0454_CT-SIM-09-13-2009 (278, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0456_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0456_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 150 ../data/train/train_selection/selection_npy/train/
183 th mdacc_HNSCC-01-0456_CT-SIM-09-13-2009 (361, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0457_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0457_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 142 ../data/train/train_selection/selection_npy/train/
184 th mdacc_HNSCC-01-0457_CT-SIM-09-13-2009 (263, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0459_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0459_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 54 ../data/train/train_selection/selection_npy/train/
185 th mdacc_HNSCC-01-0459_CT-SIM-09-13-2009 (99, 512, 512) 255.0 3.0

mdacc_HNSCC-01-0460_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0460_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 138 ../data/train/train_selection/selection_npy/train/
186 th mdacc_HNSCC-01-0460_CT-SIM-09-13-2009 (262, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0462_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0462_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 177 ../data/train/train_selection/selection_npy/train/
187 th mdacc_HNSCC-01-0462_CT-SIM-09-13-2009 (351, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0463_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0463_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 163 ../data/train/train_selection/selection_npy/train/
188 th mdacc_HNSCC-01-0463_CT-SIM-09-13-2009 (363, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0465_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0465_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 143 ../data/train/train_selection/selection_npy/train/
189 th mdacc_HNSCC-01-0465_CT-SIM-09-13-2009 (287, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0466_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0466_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 153 ../data/train/train_selection/selection_npy/train/
190 th mdacc_HNSCC-01-0466_CT-SIM-09-13-2009 (293, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0468_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0468_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 148 ../data/train/train_selection/selection_npy/train/
191 th mdacc_HNSCC-01-0468_CT-SIM-09-13-2009 (284, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0469_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0469_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 149 ../data/train/train_selection/selection_npy/train/
192 th mdacc_HNSCC-01-0469_CT-SIM-09-13-2009 (269, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0470_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0470_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 168 ../data/train/train_selection/selection_npy/train/
193 th mdacc_HNSCC-01-0470_CT-SIM-09-13-2009 (306, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0471_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0471_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 157 ../data/train/train_selection/selection_npy/train/
194 th mdacc_HNSCC-01-0471_CT-SIM-09-13-2009 (295, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0473_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0473_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 155 ../data/train/train_selection/selection_npy/train/
195 th mdacc_HNSCC-01-0473_CT-SIM-09-13-2009 (307, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0474_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0474_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 170 ../data/train/train_selection/selection_npy/train/
196 th mdacc_HNSCC-01-0474_CT-SIM-09-13-2009 (314, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0475_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0475_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 162 ../data/train/train_selection/selection_npy/train/
197 th mdacc_HNSCC-01-0475_CT-SIM-10-10-2010 (294, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0476_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0476_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 179 ../data/train/train_selection/selection_npy/train/
198 th mdacc_HNSCC-01-0476_CT-SIM-10-10-2010 (320, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0478_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0478_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 131 ../data/train/train_selection/selection_npy/train/
199 th mdacc_HNSCC-01-0478_CT-SIM-10-10-2010 (254, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0479_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0479_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 139 ../data/train/train_selection/selection_npy/train/
200 th mdacc_HNSCC-01-0479_CT-SIM-10-10-2010 (281, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0480_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0480_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 149 ../data/train/train_selection/selection_npy/train/
201 th mdacc_HNSCC-01-0480_CT-SIM-10-10-2010 (258, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0481_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0481_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 158 ../data/train/train_selection/selection_npy/train/
202 th mdacc_HNSCC-01-0481_CT-SIM-10-10-2010 (306, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0483_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0483_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 139 ../data/train/train_selection/selection_npy/train/
203 th mdacc_HNSCC-01-0483_CT-SIM-10-10-2010 (265, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0484_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0484_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 52 ../data/train/train_selection/selection_npy/train/
204 th mdacc_HNSCC-01-0484_CT-SIM-10-10-2010 (79, 512, 512) 255.0 3.0

mdacc_HNSCC-01-0485_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0485_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 132 ../data/train/train_selection/selection_npy/train/
205 th mdacc_HNSCC-01-0485_CT-SIM-10-10-2010 (246, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0486_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0486_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 166 ../data/train/train_selection/selection_npy/train/
206 th mdacc_HNSCC-01-0486_CT-SIM-10-10-2010 (296, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0488_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0488_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 137 ../data/train/train_selection/selection_npy/train/
207 th mdacc_HNSCC-01-0488_CT-SIM-10-10-2010 (278, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0489_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0489_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 122 ../data/train/train_selection/selection_npy/train/
208 th mdacc_HNSCC-01-0489_CT-SIM-10-10-2010 (252, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0491_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0491_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 130 ../data/train/train_selection/selection_npy/train/
209 th mdacc_HNSCC-01-0491_CT-SIM-10-10-2010 (265, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0492_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0492_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 44 ../data/train/train_selection/selection_npy/train/
210 th mdacc_HNSCC-01-0492_CT-SIM-10-10-2010 (73, 512, 512) 255.0 3.0

mdacc_HNSCC-01-0494_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0494_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 123 ../data/train/train_selection/selection_npy/train/
211 th mdacc_HNSCC-01-0494_CT-SIM-10-10-2010 (339, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0495_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0495_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 141 ../data/train/train_selection/selection_npy/train/
212 th mdacc_HNSCC-01-0495_CT-SIM-10-10-2010 (274, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0496_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0496_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 158 ../data/train/train_selection/selection_npy/train/
213 th mdacc_HNSCC-01-0496_CT-SIM-10-10-2010 (278, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0497_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0497_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 302 ../data/train/train_selection/selection_npy/train/
214 th mdacc_HNSCC-01-0497_CT-SIM-10-10-2010 (549, 512, 512) 255.0 0.5

mdacc_HNSCC-01-0499_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0499_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 157 ../data/train/train_selection/selection_npy/train/
215 th mdacc_HNSCC-01-0499_CT-SIM-10-10-2010 (294, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0500_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0500_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 127 ../data/train/train_selection/selection_npy/train/
216 th mdacc_HNSCC-01-0500_CT-SIM-10-10-2010 (259, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0502_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0502_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 132 ../data/train/train_selection/selection_npy/train/
217 th mdacc_HNSCC-01-0502_CT-SIM-10-10-2010 (266, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0503_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0503_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 169 ../data/train/train_selection/selection_npy/train/
218 th mdacc_HNSCC-01-0503_CT-SIM-10-10-2010 (307, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0505_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0505_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 146 ../data/train/train_selection/selection_npy/train/
219 th mdacc_HNSCC-01-0505_CT-SIM-10-10-2010 (271, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0506_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0506_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 126 ../data/train/train_selection/selection_npy/train/
220 th mdacc_HNSCC-01-0506_CT-SIM-10-10-2010 (279, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0507_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0507_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 114 ../data/train/train_selection/selection_npy/train/
221 th mdacc_HNSCC-01-0507_CT-SIM-10-10-2010 (220, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0508_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0508_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 128 ../data/train/train_selection/selection_npy/train/
222 th mdacc_HNSCC-01-0508_CT-SIM-10-10-2010 (321, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0510_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0510_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 140 ../data/train/train_selection/selection_npy/train/
223 th mdacc_HNSCC-01-0510_CT-SIM-10-10-2010 (275, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0511_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0511_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 52 ../data/train/train_selection/selection_npy/train/
224 th mdacc_HNSCC-01-0511_CT-SIM-10-10-2010 (93, 512, 512) 255.0 3.0

mdacc_HNSCC-01-0512_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0512_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 176 ../data/train/train_selection/selection_npy/train/
225 th mdacc_HNSCC-01-0512_CT-SIM-10-10-2010 (303, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0513_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0513_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 138 ../data/train/train_selection/selection_npy/train/
226 th mdacc_HNSCC-01-0513_CT-SIM-10-10-2010 (267, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0516_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0516_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 139 ../data/train/train_selection/selection_npy/train/
227 th mdacc_HNSCC-01-0516_CT-SIM-10-10-2010 (346, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0517_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0517_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 129 ../data/train/train_selection/selection_npy/train/
228 th mdacc_HNSCC-01-0517_CT-SIM-10-10-2010 (261, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0518_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0518_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 138 ../data/train/train_selection/selection_npy/train/
229 th mdacc_HNSCC-01-0518_CT-SIM-10-10-2010 (255, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0519_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0519_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 151 ../data/train/train_selection/selection_npy/train/
230 th mdacc_HNSCC-01-0519_CT-SIM-10-10-2010 (279, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0522_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0522_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 143 ../data/train/train_selection/selection_npy/train/
231 th mdacc_HNSCC-01-0522_CT-SIM-10-10-2010 (268, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0523_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0523_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 131 ../data/train/train_selection/selection_npy/train/
232 th mdacc_HNSCC-01-0523_CT-SIM-10-10-2010 (256, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0524_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0524_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 161 ../data/train/train_selection/selection_npy/train/
233 th mdacc_HNSCC-01-0524_CT-SIM-10-10-2010 (291, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0525_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0525_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 112 ../data/train/train_selection/selection_npy/train/
234 th mdacc_HNSCC-01-0525_CT-SIM-10-10-2010 (234, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0527_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0527_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 151 ../data/train/train_selection/selection_npy/train/
235 th mdacc_HNSCC-01-0527_CT-SIM-10-10-2010 (264, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0528_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0528_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 131 ../data/train/train_selection/selection_npy/train/

236 th mdacc_HNSCC-01-0528_CT-SIM-10-10-2010 (231, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0529_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0529_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 132 ../data/train/train_selection/selection_npy/train/
237 th mdacc_HNSCC-01-0529_CT-SIM-10-10-2010 (272, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0530_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0530_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 141 ../data/train/train_selection/selection_npy/train/
238 th mdacc_HNSCC-01-0530_CT-SIM-10-10-2010 (349, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0532_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0532_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 149 ../data/train/train_selection/selection_npy/train/
239 th mdacc_HNSCC-01-0532_CT-SIM-10-10-2010 (299, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0534_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0534_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 128 ../data/train/train_selection/selection_npy/train/
240 th mdacc_HNSCC-01-0534_CT-SIM-10-10-2010 (265, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0535_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0535_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 67 ../data/train/train_selection/selection_npy/train/
241 th mdacc_HNSCC-01-0535_CT-SIM-10-10-2010 (124, 512, 512) 255.0 2.0

mdacc_HNSCC-01-0536_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0536_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 139 ../data/train/train_selection/selection_npy/train/
242 th mdacc_HNSCC-01-0536_CT-SIM-10-10-2010 (250, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0538_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0538_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 150 ../data/train/train_selection/selection_npy/train/
243 th mdacc_HNSCC-01-0538_CT-SIM-10-10-2010 (277, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0539_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0539_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 164 ../data/train/train_selection/selection_npy/train/
244 th mdacc_HNSCC-01-0539_CT-SIM-10-10-2010 (304, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0540_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0540_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 136 ../data/train/train_selection/selection_npy/train/
245 th mdacc_HNSCC-01-0540_CT-SIM-10-10-2010 (245, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0541_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0541_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 164 ../data/train/train_selection/selection_npy/train/
246 th mdacc_HNSCC-01-0541_CT-SIM-10-10-2010 (327, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0543_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0543_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 145 ../data/train/train_selection/selection_npy/train/
247 th mdacc_HNSCC-01-0543_CT-SIM-11-13-2011 (264, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0544_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0544_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 144 ../data/train/train_selection/selection_npy/train/
248 th mdacc_HNSCC-01-0544_CT-SIM-10-10-2010 (262, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0545_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0545_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 146 ../data/train/train_selection/selection_npy/train/
249 th mdacc_HNSCC-01-0545_CT-SIM-10-10-2010 (280, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0546_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0546_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 137 ../data/train/train_selection/selection_npy/train/
250 th mdacc_HNSCC-01-0546_CT-SIM-10-10-2010 (262, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0548_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0548_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 170 ../data/train/train_selection/selection_npy/train/
251 th mdacc_HNSCC-01-0548_CT-SIM-10-10-2010 (289, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0549_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0549_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 151 ../data/train/train_selection/selection_npy/train/
252 th mdacc_HNSCC-01-0549_CT-SIM-10-10-2010 (261, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0550_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0550_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 175 ../data/train/train_selection/selection_npy/train/
253 th mdacc_HNSCC-01-0550_CT-SIM-10-10-2010 (306, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0551_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0551_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 80 ../data/train/train_selection/selection_npy/train/
254 th mdacc_HNSCC-01-0551_CT-SIM-10-10-2010 (135, 512, 512) 255.0 2.0

mdacc_HNSCC-01-0553_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0553_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 51 ../data/train/train_selection/selection_npy/train/
255 th mdacc_HNSCC-01-0553_CT-SIM-11-13-2011 (98, 512, 512) 255.0 2.0

mdacc_HNSCC-01-0554_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0554_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 125 ../data/train/train_selection/selection_npy/train/
256 th mdacc_HNSCC-01-0554_CT-SIM-11-13-2011 (246, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0555_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0555_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 139 ../data/train/train_selection/selection_npy/train/
257 th mdacc_HNSCC-01-0555_CT-SIM-11-13-2011 (348, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0556_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0556_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 139 ../data/train/train_selection/selection_npy/train/
258 th mdacc_HNSCC-01-0556_CT-SIM-11-13-2011 (284, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0558_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0558_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 125 ../data/train/train_selection/selection_npy/train/
259 th mdacc_HNSCC-01-0558_CT-SIM-11-13-2011 (279, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0559_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0559_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 155 ../data/train/train_selection/selection_npy/train/
260 th mdacc_HNSCC-01-0559_CT-SIM-11-13-2011 (302, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0560_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0560_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 128 ../data/train/train_selection/selection_npy/train/
261 th mdacc_HNSCC-01-0560_CT-SIM-11-13-2011 (253, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0561_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0561_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 32 ../data/train/train_selection/selection_npy/train/
262 th mdacc_HNSCC-01-0561_CT-SIM-11-13-2011 (69, 512, 512) 255.0 3.0

mdacc_HNSCC-01-0563_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0563_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 134 ../data/train/train_selection/selection_npy/train/
263 th mdacc_HNSCC-01-0563_CT-SIM-11-13-2011 (266, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0564_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0564_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 157 ../data/train/train_selection/selection_npy/train/
264 th mdacc_HNSCC-01-0564_CT-SIM-11-13-2011 (286, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0565_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0565_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 171 ../data/train/train_selection/selection_npy/train/
265 th mdacc_HNSCC-01-0565_CT-SIM-11-13-2011 (387, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0566_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0566_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 154 ../data/train/train_selection/selection_npy/train/
266 th mdacc_HNSCC-01-0566_CT-SIM-11-13-2011 (277, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0568_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0568_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 55 ../data/train/train_selection/selection_npy/train/
267 th mdacc_HNSCC-01-0568_CT-SIM-11-13-2011 (101, 512, 512) 255.0 2.5

mdacc_HNSCC-01-0570_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0570_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 175 ../data/train/train_selection/selection_npy/train/
268 th mdacc_HNSCC-01-0570_CT-SIM-11-13-2011 (328, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0571_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0571_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 149 ../data/train/train_selection/selection_npy/train/
269 th mdacc_HNSCC-01-0571_CT-SIM-11-13-2011 (275, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0572_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0572_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 151 ../data/train/train_selection/selection_npy/train/
270 th mdacc_HNSCC-01-0572_CT-SIM-11-13-2011 (275, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0574_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0574_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 121 ../data/train/train_selection/selection_npy/train/
271 th mdacc_HNSCC-01-0574_CT-SIM-11-13-2011 (272, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0576_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0576_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 75 ../data/train/train_selection/selection_npy/train/
272 th mdacc_HNSCC-01-0576_CT-SIM-11-13-2011 (100, 512, 512) 255.0 2.5

mdacc_HNSCC-01-0578_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0578_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 49 ../data/train/train_selection/selection_npy/train/
273 th mdacc_HNSCC-01-0578_CT-SIM-11-13-2011 (98, 512, 512) 255.0 3.0

mdacc_HNSCC-01-0580_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0580_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 164 ../data/train/train_selection/selection_npy/train/
274 th mdacc_HNSCC-01-0580_CT-SIM-11-13-2011 (325, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0581_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0581_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 156 ../data/train/train_selection/selection_npy/train/
275 th mdacc_HNSCC-01-0581_CT-SIM-11-13-2011 (283, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0582_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0582_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 54 ../data/train/train_selection/selection_npy/train/
276 th mdacc_HNSCC-01-0582_CT-SIM-11-13-2011 (87, 512, 512) 255.0 3.0

mdacc_HNSCC-01-0583_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0583_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 147 ../data/train/train_selection/selection_npy/train/
277 th mdacc_HNSCC-01-0583_CT-SIM-11-13-2011 (283, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0585_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0585_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 138 ../data/train/train_selection/selection_npy/train/
278 th mdacc_HNSCC-01-0585_CT-SIM-11-13-2011 (274, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0587_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0587_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 166 ../data/train/train_selection/selection_npy/train/
279 th mdacc_HNSCC-01-0587_CT-SIM-11-13-2011 (302, 512, 512) 255.0 1.0

mdacc_HNSCC-01-0588_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0588_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 118 ../data/train/train_selection/selection_npy/train/
280 th mdacc_HNSCC-01-0588_CT-SIM-11-13-2011 (247, 512, 512) 255.0 1.0

In [5]:
#### Slice prediction model data preparation - VALIDATION
# The z-offset for a slice should represent its offset above or below the C3 slice in mm 
# Slices below the chosen C3 slice should be given negative offsets.
df_to_be_writen = pd.DataFrame()
df_train = df_all[df_all.Datatype.isin(['val'])]
image_dir = '../data/raw-data/scans/'
targ_dir = '../data/train/train_prediction/prediction_npy/val/'
csv_write_path = '../data/train/train_prediction/prediction_meta/val.csv'
j = 0
for idx in range(df_train.shape[0]):
    image_path = image_dir + df_train.iloc[idx,0]+'.nrrd'
    patient_id =df_train.iloc[idx,0][:37]
    c3_slice = df_train.iloc[idx,1]
    print(patient_id,image_path,c3_slice,targ_dir)
     
    image_sitk =  sitk.ReadImage(image_path)
    image_array  = sitk.GetArrayFromImage(image_sitk)
    spacing =  image_sitk.GetSpacing()[2]
    
    image_array = apply_window(image_array)
    windowed_images = image_array

    print(idx+1,'th',patient_id ,image_array.shape,np.max(image_array))

    resize_func = functools.partial(resize, output_shape=[256,256],
                                    preserve_range=True, anti_aliasing=True, mode='constant')
    series = np.dstack([resize_func(im) for im in windowed_images])
    series = np.transpose(series[:, :, :, np.newaxis], [2, 0, 1, 3])
#     print(type(series),series.shape)
    for slice_idx in range(image_array.shape[0]):
        offset = spacing*(slice_idx-c3_slice)
        offset = round(offset,5)
        npy_name = str(j).zfill(6)+'_'+patient_id+'.npy'
        npy_path = targ_dir +npy_name
        im_array = series[slice_idx,:,:,:].astype(np.uint8)
        np.save(npy_path,im_array)
#         print(npy_path ,im_array.shape,'spacing',spacing)

        df_offset = pd.DataFrame({'NPY_name':npy_name,
                       'ZOffset':offset},index=[0])
        df_to_be_writen = pd.concat([df_to_be_writen,df_offset])
        df_to_be_writen.to_csv(csv_write_path)   
        j=j+1
    print()

mdacc_HNSCC-01-0216_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0216_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 192 ../data/train/train_selection/selection_npy/val/
1 th mdacc_HNSCC-01-0216_CT-SIM-08-10-2008 (287, 512, 512) 255.0

mdacc_HNSCC-01-0221_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0221_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 161 ../data/train/train_selection/selection_npy/val/
2 th mdacc_HNSCC-01-0221_CT-SIM-08-10-2008 (271, 512, 512) 255.0

mdacc_HNSCC-01-0231_CT-SIM-05-08-2005 ../data/raw-data/scans/mdacc_HNSCC-01-0231_CT-SIM-05-08-2005-_raw_raw_raw_xx.nrrd 188 ../data/train/train_selection/selection_npy/val/
3 th mdacc_HNSCC-01-0231_CT-SIM-05-08-2005 (288, 512, 512) 255.0

mdacc_HNSCC-01-0236_CT-SIM-05-08-2005 ../data/raw-data/scans/mdacc_HNSCC-01-0236_CT-SIM-05-08-2005-_raw_raw_raw_xx.nrrd 160 ../data/train/train_selection/selection_npy/val/
4 th mdacc_HNSCC-01-0236_CT-SIM-05-08-2005 (250, 512, 512) 255.0

mdacc_HNSCC-01-0241_CT-SIM-05-08-2005 ../data/raw-data/scans/mdacc_HNSCC-01-0241_CT-SIM-05-08-2005-_raw_raw_raw_xx.nrrd 47 ../data/train/train_selection/selection_npy/val/
5 th mdacc_HNSCC-01-0241_CT-SIM-05-08-2005 (95, 512, 512) 255.0

mdacc_HNSCC-01-0246_CT-SIM-05-08-2005 ../data/raw-data/scans/mdacc_HNSCC-01-0246_CT-SIM-05-08-2005-_raw_raw_raw_xx.nrrd 192 ../data/train/train_selection/selection_npy/val/
6 th mdacc_HNSCC-01-0246_CT-SIM-05-08-2005 (289, 512, 512) 255.0

mdacc_HNSCC-01-0251_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0251_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 33 ../data/train/train_selection/selection_npy/val/
7 th mdacc_HNSCC-01-0251_CT-SIM-06-11-2006 (76, 512, 512) 255.0

mdacc_HNSCC-01-0256_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0256_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 161 ../data/train/train_selection/selection_npy/val/
8 th mdacc_HNSCC-01-0256_CT-SIM-06-11-2006 (253, 512, 512) 255.0

mdacc_HNSCC-01-0261_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0261_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 175 ../data/train/train_selection/selection_npy/val/
9 th mdacc_HNSCC-01-0261_CT-SIM-06-11-2006 (289, 512, 512) 255.0

mdacc_HNSCC-01-0266_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0266_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 139 ../data/train/train_selection/selection_npy/val/
10 th mdacc_HNSCC-01-0266_CT-SIM-06-11-2006 (224, 512, 512) 255.0

mdacc_HNSCC-01-0272_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0272_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 132 ../data/train/train_selection/selection_npy/val/
11 th mdacc_HNSCC-01-0272_CT-SIM-06-11-2006 (214, 512, 512) 255.0

mdacc_HNSCC-01-0277_CT-SIM-06-11-2006 ../data/raw-data/scans/mdacc_HNSCC-01-0277_CT-SIM-06-11-2006-_raw_raw_raw_xx.nrrd 56 ../data/train/train_selection/selection_npy/val/
12 th mdacc_HNSCC-01-0277_CT-SIM-06-11-2006 (99, 512, 512) 255.0

mdacc_HNSCC-01-0284_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0284_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 150 ../data/train/train_selection/selection_npy/val/
13 th mdacc_HNSCC-01-0284_CT-SIM-07-08-2007 (254, 512, 512) 255.0

mdacc_HNSCC-01-0289_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0289_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 152 ../data/train/train_selection/selection_npy/val/
14 th mdacc_HNSCC-01-0289_CT-SIM-07-08-2007 (244, 512, 512) 255.0

mdacc_HNSCC-01-0294_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0294_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 208 ../data/train/train_selection/selection_npy/val/
15 th mdacc_HNSCC-01-0294_CT-SIM-07-08-2007 (345, 512, 512) 255.0

mdacc_HNSCC-01-0301_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0301_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 159 ../data/train/train_selection/selection_npy/val/
16 th mdacc_HNSCC-01-0301_CT-SIM-07-08-2007 (257, 512, 512) 255.0

mdacc_HNSCC-01-0306_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0306_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 136 ../data/train/train_selection/selection_npy/val/
17 th mdacc_HNSCC-01-0306_CT-SIM-07-08-2007 (259, 512, 512) 255.0

mdacc_HNSCC-01-0312_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0312_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 69 ../data/train/train_selection/selection_npy/val/
18 th mdacc_HNSCC-01-0312_CT-SIM-07-08-2007 (116, 512, 512) 255.0

mdacc_HNSCC-01-0317_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0317_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 145 ../data/train/train_selection/selection_npy/val/
19 th mdacc_HNSCC-01-0317_CT-SIM-07-08-2007 (249, 512, 512) 255.0

mdacc_HNSCC-01-0322_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0322_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 50 ../data/train/train_selection/selection_npy/val/
20 th mdacc_HNSCC-01-0322_CT-SIM-07-08-2007 (86, 512, 512) 255.0

mdacc_HNSCC-01-0327_CT-SIM-07-08-2007 ../data/raw-data/scans/mdacc_HNSCC-01-0327_CT-SIM-07-08-2007-_raw_raw_raw_xx.nrrd 147 ../data/train/train_selection/selection_npy/val/
21 th mdacc_HNSCC-01-0327_CT-SIM-07-08-2007 (359, 512, 512) 255.0

mdacc_HNSCC-01-0332_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0332_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 151 ../data/train/train_selection/selection_npy/val/
22 th mdacc_HNSCC-01-0332_CT-SIM-08-10-2008 (262, 512, 512) 255.0

mdacc_HNSCC-01-0337_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0337_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 162 ../data/train/train_selection/selection_npy/val/
23 th mdacc_HNSCC-01-0337_CT-SIM-08-10-2008 (250, 512, 512) 255.0

mdacc_HNSCC-01-0343_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0343_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 156 ../data/train/train_selection/selection_npy/val/
24 th mdacc_HNSCC-01-0343_CT-SIM-08-10-2008 (257, 512, 512) 255.0

mdacc_HNSCC-01-0348_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0348_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 220 ../data/train/train_selection/selection_npy/val/
25 th mdacc_HNSCC-01-0348_CT-SIM-08-10-2008 (427, 512, 512) 255.0

mdacc_HNSCC-01-0354_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0354_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 144 ../data/train/train_selection/selection_npy/val/
26 th mdacc_HNSCC-01-0354_CT-SIM-08-10-2008 (350, 512, 512) 255.0

mdacc_HNSCC-01-0359_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0359_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 183 ../data/train/train_selection/selection_npy/val/
27 th mdacc_HNSCC-01-0359_CT-SIM-08-10-2008 (286, 512, 512) 255.0

mdacc_HNSCC-01-0364_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0364_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 143 ../data/train/train_selection/selection_npy/val/
28 th mdacc_HNSCC-01-0364_CT-SIM-08-10-2008 (265, 512, 512) 255.0

mdacc_HNSCC-01-0369_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0369_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 176 ../data/train/train_selection/selection_npy/val/
29 th mdacc_HNSCC-01-0369_CT-SIM-08-10-2008 (274, 512, 512) 255.0

mdacc_HNSCC-01-0374_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0374_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 143 ../data/train/train_selection/selection_npy/val/
30 th mdacc_HNSCC-01-0374_CT-SIM-08-10-2008 (362, 512, 512) 255.0

mdacc_HNSCC-01-0379_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0379_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 198 ../data/train/train_selection/selection_npy/val/
31 th mdacc_HNSCC-01-0379_CT-SIM-08-10-2008 (292, 512, 512) 255.0

mdacc_HNSCC-01-0384_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0384_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 171 ../data/train/train_selection/selection_npy/val/
32 th mdacc_HNSCC-01-0384_CT-SIM-08-10-2008 (255, 512, 512) 255.0

mdacc_HNSCC-01-0389_CT-SIM-08-10-2008 ../data/raw-data/scans/mdacc_HNSCC-01-0389_CT-SIM-08-10-2008-_raw_raw_raw_xx.nrrd 187 ../data/train/train_selection/selection_npy/val/
33 th mdacc_HNSCC-01-0389_CT-SIM-08-10-2008 (288, 512, 512) 255.0

mdacc_HNSCC-01-0394_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0394_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 154 ../data/train/train_selection/selection_npy/val/
34 th mdacc_HNSCC-01-0394_CT-SIM-09-13-2009 (245, 512, 512) 255.0

mdacc_HNSCC-01-0399_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0399_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 148 ../data/train/train_selection/selection_npy/val/

35 th mdacc_HNSCC-01-0399_CT-SIM-09-13-2009 (217, 512, 512) 255.0

mdacc_HNSCC-01-0404_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0404_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 61 ../data/train/train_selection/selection_npy/val/
36 th mdacc_HNSCC-01-0404_CT-SIM-09-13-2009 (119, 512, 512) 255.0

mdacc_HNSCC-01-0409_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0409_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 154 ../data/train/train_selection/selection_npy/val/
37 th mdacc_HNSCC-01-0409_CT-SIM-09-13-2009 (239, 512, 512) 255.0

mdacc_HNSCC-01-0414_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0414_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 174 ../data/train/train_selection/selection_npy/val/
38 th mdacc_HNSCC-01-0414_CT-SIM-09-13-2009 (285, 512, 512) 255.0

mdacc_HNSCC-01-0419_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0419_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 176 ../data/train/train_selection/selection_npy/val/
39 th mdacc_HNSCC-01-0419_CT-SIM-09-13-2009 (259, 512, 512) 255.0

mdacc_HNSCC-01-0424_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0424_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 176 ../data/train/train_selection/selection_npy/val/
40 th mdacc_HNSCC-01-0424_CT-SIM-09-13-2009 (274, 512, 512) 255.0

mdacc_HNSCC-01-0429_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0429_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 153 ../data/train/train_selection/selection_npy/val/
41 th mdacc_HNSCC-01-0429_CT-SIM-09-13-2009 (353, 512, 512) 255.0

mdacc_HNSCC-01-0434_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0434_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 150 ../data/train/train_selection/selection_npy/val/
42 th mdacc_HNSCC-01-0434_CT-SIM-09-13-2009 (261, 512, 512) 255.0

mdacc_HNSCC-01-0440_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0440_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 169 ../data/train/train_selection/selection_npy/val/
43 th mdacc_HNSCC-01-0440_CT-SIM-09-13-2009 (307, 512, 512) 255.0

mdacc_HNSCC-01-0445_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0445_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 186 ../data/train/train_selection/selection_npy/val/
44 th mdacc_HNSCC-01-0445_CT-SIM-09-13-2009 (387, 512, 512) 255.0

mdacc_HNSCC-01-0450_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0450_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 145 ../data/train/train_selection/selection_npy/val/
45 th mdacc_HNSCC-01-0450_CT-SIM-09-13-2009 (267, 512, 512) 255.0

mdacc_HNSCC-01-0455_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0455_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 136 ../data/train/train_selection/selection_npy/val/
46 th mdacc_HNSCC-01-0455_CT-SIM-09-13-2009 (279, 512, 512) 255.0

mdacc_HNSCC-01-0461_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0461_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 45 ../data/train/train_selection/selection_npy/val/
47 th mdacc_HNSCC-01-0461_CT-SIM-09-13-2009 (87, 512, 512) 255.0

mdacc_HNSCC-01-0467_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0467_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 179 ../data/train/train_selection/selection_npy/val/
48 th mdacc_HNSCC-01-0467_CT-SIM-09-13-2009 (307, 512, 512) 255.0

mdacc_HNSCC-01-0472_CT-SIM-09-13-2009 ../data/raw-data/scans/mdacc_HNSCC-01-0472_CT-SIM-09-13-2009-_raw_raw_raw_xx.nrrd 149 ../data/train/train_selection/selection_npy/val/
49 th mdacc_HNSCC-01-0472_CT-SIM-09-13-2009 (296, 512, 512) 255.0

mdacc_HNSCC-01-0477_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0477_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 173 ../data/train/train_selection/selection_npy/val/
50 th mdacc_HNSCC-01-0477_CT-SIM-10-10-2010 (311, 512, 512) 255.0

mdacc_HNSCC-01-0482_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0482_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 50 ../data/train/train_selection/selection_npy/val/
51 th mdacc_HNSCC-01-0482_CT-SIM-10-10-2010 (105, 512, 512) 255.0

mdacc_HNSCC-01-0487_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0487_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 37 ../data/train/train_selection/selection_npy/val/
52 th mdacc_HNSCC-01-0487_CT-SIM-10-10-2010 (75, 512, 512) 255.0

mdacc_HNSCC-01-0493_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0493_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 123 ../data/train/train_selection/selection_npy/val/
53 th mdacc_HNSCC-01-0493_CT-SIM-10-10-2010 (259, 512, 512) 255.0

mdacc_HNSCC-01-0498_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0498_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 39 ../data/train/train_selection/selection_npy/val/
54 th mdacc_HNSCC-01-0498_CT-SIM-10-10-2010 (72, 512, 512) 255.0

mdacc_HNSCC-01-0504_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0504_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 159 ../data/train/train_selection/selection_npy/val/
55 th mdacc_HNSCC-01-0504_CT-SIM-10-10-2010 (277, 512, 512) 255.0

mdacc_HNSCC-01-0509_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0509_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 159 ../data/train/train_selection/selection_npy/val/
56 th mdacc_HNSCC-01-0509_CT-SIM-10-10-2010 (297, 512, 512) 255.0

mdacc_HNSCC-01-0514_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0514_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 149 ../data/train/train_selection/selection_npy/val/
57 th mdacc_HNSCC-01-0514_CT-SIM-10-10-2010 (353, 512, 512) 255.0

mdacc_HNSCC-01-0521_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0521_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 131 ../data/train/train_selection/selection_npy/val/
58 th mdacc_HNSCC-01-0521_CT-SIM-10-10-2010 (236, 512, 512) 255.0

mdacc_HNSCC-01-0526_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0526_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 142 ../data/train/train_selection/selection_npy/val/
59 th mdacc_HNSCC-01-0526_CT-SIM-10-10-2010 (265, 512, 512) 255.0

mdacc_HNSCC-01-0531_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0531_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 154 ../data/train/train_selection/selection_npy/val/
60 th mdacc_HNSCC-01-0531_CT-SIM-10-10-2010 (281, 512, 512) 255.0

mdacc_HNSCC-01-0537_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0537_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 137 ../data/train/train_selection/selection_npy/val/
61 th mdacc_HNSCC-01-0537_CT-SIM-11-13-2011 (270, 512, 512) 255.0

mdacc_HNSCC-01-0542_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0542_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 152 ../data/train/train_selection/selection_npy/val/
62 th mdacc_HNSCC-01-0542_CT-SIM-10-10-2010 (355, 512, 512) 255.0

mdacc_HNSCC-01-0547_CT-SIM-10-10-2010 ../data/raw-data/scans/mdacc_HNSCC-01-0547_CT-SIM-10-10-2010-_raw_raw_raw_xx.nrrd 136 ../data/train/train_selection/selection_npy/val/
63 th mdacc_HNSCC-01-0547_CT-SIM-10-10-2010 (250, 512, 512) 255.0

mdacc_HNSCC-01-0552_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0552_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 160 ../data/train/train_selection/selection_npy/val/
64 th mdacc_HNSCC-01-0552_CT-SIM-11-13-2011 (289, 512, 512) 255.0

mdacc_HNSCC-01-0557_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0557_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 133 ../data/train/train_selection/selection_npy/val/
65 th mdacc_HNSCC-01-0557_CT-SIM-11-13-2011 (268, 512, 512) 255.0

mdacc_HNSCC-01-0562_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0562_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 159 ../data/train/train_selection/selection_npy/val/
66 th mdacc_HNSCC-01-0562_CT-SIM-11-13-2011 (287, 512, 512) 255.0

mdacc_HNSCC-01-0567_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0567_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 175 ../data/train/train_selection/selection_npy/val/
67 th mdacc_HNSCC-01-0567_CT-SIM-11-13-2011 (293, 512, 512) 255.0

mdacc_HNSCC-01-0573_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0573_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 57 ../data/train/train_selection/selection_npy/val/
68 th mdacc_HNSCC-01-0573_CT-SIM-11-13-2011 (109, 512, 512) 255.0

mdacc_HNSCC-01-0579_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0579_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 178 ../data/train/train_selection/selection_npy/val/
69 th mdacc_HNSCC-01-0579_CT-SIM-11-13-2011 (321, 512, 512) 255.0

mdacc_HNSCC-01-0584_CT-SIM-11-13-2011 ../data/raw-data/scans/mdacc_HNSCC-01-0584_CT-SIM-11-13-2011-_raw_raw_raw_xx.nrrd 159 ../data/train/train_selection/selection_npy/val/
70 th mdacc_HNSCC-01-0584_CT-SIM-11-13-2011 (303, 512, 512) 255.0

In [1]:
#### Segmentation model data preparation 

import pandas as pd
from pprint import pprint
df_c3_annotation = pd.read_csv('../data/raw-data/Slice_Annotation.csv', index_col = 0)

print(df_c3_annotation.shape)
(df_c3_annotation.head())

(390, 5)

,patient_id,C3_Manual_slice,Datatype,Z_spacing,XY_spacing
0,mdacc_HNSCC-01-0216_CT-SIM-08-10-2008-_raw_raw...,192,val,NaN,NaN
0,mdacc_HNSCC-01-0217_CT-SIM-12-16-2012-_raw_raw...,131,train,NaN,NaN
0,mdacc_HNSCC-01-0218_CT-SIM-09-13-2009-_raw_raw...,166,train,NaN,NaN
0,mdacc_HNSCC-01-0219_CT-SIM-09-13-2009-_raw_raw...,150,train,NaN,NaN
0,mdacc_HNSCC-01-0220_CT-SIM-11-13-2011-_raw_raw...,129,train,NaN,NaN

In [2]:
import os
import glob
import random

#image_folder ='../ct_scan_in_nifti/'
#mask_folder = '../ct_scan_C3_expert_segmentation_in_nifti/'
image_folder ='../data/raw-data/scans-normalized/'
mask_folder = '../data/raw-data/segs-normalized/'

images = sorted(glob.glob(os.path.join(image_folder)+'/*.nrrd'))
masks = sorted(glob.glob(os.path.join(mask_folder)+'/*.nrrd'))
[train_images, train_masks, val_images, val_masks] = [[],[],[],[]]
print('The number of CT images:',len(images),'The number of segmentation masks:',len(masks))

train_slices = []
val_slices = []

for idx,row in df_c3_annotation.iterrows():
    image_name = row['patient_id']+'.nrrd'
    mask_name = row['patient_id']+'.seg.nrrd'
    if os.path.exists(image_folder+image_name) and os.path.exists(mask_folder+mask_name):
        if (row['Datatype'] == 'train'):
            train_images.append(image_folder+image_name)
            train_masks.append(mask_folder+mask_name)
            train_slices.append(row['C3_Manual_slice'])
        if (row['Datatype'] == 'val'):
            val_images.append(image_folder+image_name)
            val_masks.append(mask_folder+mask_name)
            val_slices.append(row['C3_Manual_slice'])

print(len(train_images),len(train_masks),len(train_slices))
print(len(val_images),len(val_masks),len(val_slices))

The number of CT images: 390 The number of segmentation masks: 390
247 247 247
62 62 62

In [3]:
import numpy as np
import SimpleITK as sitk

train_images_array =  np.zeros((len(train_images),512,512,1))
val_images_array  = np.zeros((len(val_images),512,512,1))

train_masks_array  = np.zeros((len(train_images),512,512,1))
val_masks_array  = np.zeros((len(val_images),512,512,1))

In [4]:
images = train_images
labels = train_masks

for i in range(len(images)):
    if (images[i].split('/')[-1][:38]==labels[i].split('/')[-1][:38]):
        print(i+1,'th processing:___'+images[i].split('/')[-1][:38])
        image_sitk = sitk.ReadImage(images[i])
        label_sitk = sitk.ReadImage(labels[i])
        
        seg_slice = train_slices[i]
        
        image_array  = sitk.GetArrayFromImage(image_sitk)[seg_slice,:,:].reshape(1,512,512,1)
        label_array  = sitk.GetArrayFromImage(label_sitk )[seg_slice,:,:].reshape(1,512,512,1)
        print(np.sum(label_array))
        train_images_array[i,:,:,:] = image_array
        train_masks_array[i,:,:,:] = label_array
        print()
train_masks_array=train_masks_array.astype(np.uint8)

np.save('../data/train/train_segmentation/train_images.npy',train_images_array)
np.save('../data/train/train_segmentation/train_masks.npy',train_masks_array)

1 th processing:___mdacc_HNSCC-01-0217_CT-SIM-12-16-2012-
12591.0

2 th processing:___mdacc_HNSCC-01-0218_CT-SIM-09-13-2009-
20226.0

3 th processing:___mdacc_HNSCC-01-0219_CT-SIM-09-13-2009-
12748.0

4 th processing:___mdacc_HNSCC-01-0220_CT-SIM-11-13-2011-
15063.0

5 th processing:___mdacc_HNSCC-01-0222_CT-SIM-09-13-2009-
10958.0

6 th processing:___mdacc_HNSCC-01-0223_CT-SIM-10-10-2010-
11981.0

7 th processing:___mdacc_HNSCC-01-0224_CT-SIM-07-08-2007-
12384.0

8 th processing:___mdacc_HNSCC-01-0230_CT-SIM-05-08-2005-
13431.0

9 th processing:___mdacc_HNSCC-01-0232_CT-SIM-05-08-2005-
21591.0

10 th processing:___mdacc_HNSCC-01-0233_CT-SIM-05-08-2005-
17375.0

11 th processing:___mdacc_HNSCC-01-0234_CT-SIM-05-08-2005-
19633.0

12 th processing:___mdacc_HNSCC-01-0235_CT-SIM-05-08-2005-
17977.0

13 th processing:___mdacc_HNSCC-01-0237_CT-SIM-05-08-2005-
16415.0

14 th processing:___mdacc_HNSCC-01-0238_CT-SIM-05-08-2005-
21586.0

15 th processing:___mdacc_HNSCC-01-0239_CT-SIM-05-08-2005-
32147.0

16 th processing:___mdacc_HNSCC-01-0240_CT-SIM-05-08-2005-
19322.0

17 th processing:___mdacc_HNSCC-01-0242_CT-SIM-05-08-2005-
17676.0

18 th processing:___mdacc_HNSCC-01-0243_CT-SIM-05-08-2005-
17164.0

19 th processing:___mdacc_HNSCC-01-0244_CT-SIM-05-08-2005-
18784.0

20 th processing:___mdacc_HNSCC-01-0245_CT-SIM-05-08-2005-
20926.0

21 th processing:___mdacc_HNSCC-01-0247_CT-SIM-05-08-2005-
19670.0

22 th processing:___mdacc_HNSCC-01-0248_CT-SIM-05-08-2005-
15717.0

23 th processing:___mdacc_HNSCC-01-0249_CT-SIM-05-08-2005-
28405.0

24 th processing:___mdacc_HNSCC-01-0250_CT-SIM-05-08-2005-
24793.0

25 th processing:___mdacc_HNSCC-01-0252_CT-SIM-05-08-2005-
19991.0

26 th processing:___mdacc_HNSCC-01-0253_CT-SIM-06-11-2006-
19732.0

27 th processing:___mdacc_HNSCC-01-0254_CT-SIM-06-11-2006-
16270.0

28 th processing:___mdacc_HNSCC-01-0255_CT-SIM-06-11-2006-
10214.0

29 th processing:___mdacc_HNSCC-01-0257_CT-SIM-06-11-2006-
25762.0

30 th processing:___mdacc_HNSCC-01-0258_CT-SIM-06-11-2006-
11988.0

31 th processing:___mdacc_HNSCC-01-0259_CT-SIM-06-11-2006-
17295.0

32 th processing:___mdacc_HNSCC-01-0260_CT-SIM-06-11-2006-
31919.0

33 th processing:___mdacc_HNSCC-01-0262_CT-SIM-06-11-2006-
19630.0

34 th processing:___mdacc_HNSCC-01-0263_CT-SIM-06-11-2006-
10197.0

35 th processing:___mdacc_HNSCC-01-0264_CT-SIM-06-11-2006-
19174.0

36 th processing:___mdacc_HNSCC-01-0265_CT-SIM-06-11-2006-
18115.0

37 th processing:___mdacc_HNSCC-01-0267_CT-SIM-06-11-2006-
24378.0

38 th processing:___mdacc_HNSCC-01-0268_CT-SIM-06-11-2006-
28766.0

39 th processing:___mdacc_HNSCC-01-0269_CT-SIM-06-11-2006-
17046.0

40 th processing:___mdacc_HNSCC-01-0271_CT-SIM-06-11-2006-
23228.0

41 th processing:___mdacc_HNSCC-01-0273_CT-SIM-06-11-2006-
28344.0

42 th processing:___mdacc_HNSCC-01-0274_CT-SIM-06-11-2006-
18125.0

43 th processing:___mdacc_HNSCC-01-0275_CT-SIM-06-11-2006-
16439.0

44 th processing:___mdacc_HNSCC-01-0276_CT-SIM-06-11-2006-
19514.0

45 th processing:___mdacc_HNSCC-01-0278_CT-SIM-06-11-2006-
16579.0

46 th processing:___mdacc_HNSCC-01-0281_CT-SIM-08-10-2008-
11764.0

47 th processing:___mdacc_HNSCC-01-0282_CT-SIM-06-11-2006-
12572.0

48 th processing:___mdacc_HNSCC-01-0283_CT-SIM-06-11-2006-
15072.0

49 th processing:___mdacc_HNSCC-01-0285_CT-SIM-06-11-2006-
19501.0

50 th processing:___mdacc_HNSCC-01-0286_CT-SIM-06-11-2006-
17454.0

51 th processing:___mdacc_HNSCC-01-0287_CT-SIM-07-08-2007-
15377.0

52 th processing:___mdacc_HNSCC-01-0288_CT-SIM-07-08-2007-
19388.0

53 th processing:___mdacc_HNSCC-01-0290_CT-SIM-07-08-2007-
15750.0

54 th processing:___mdacc_HNSCC-01-0291_CT-SIM-07-08-2007-
21691.0

55 th processing:___mdacc_HNSCC-01-0292_CT-SIM-07-08-2007-
15407.0

56 th processing:___mdacc_HNSCC-01-0293_CT-SIM-07-08-2007-
17343.0

57 th processing:___mdacc_HNSCC-01-0296_CT-SIM-07-08-2007-
16848.0

58 th processing:___mdacc_HNSCC-01-0297_CT-SIM-07-08-2007-
18321.0

59 th processing:___mdacc_HNSCC-01-0299_CT-SIM-07-08-2007-
15324.0

60 th processing:___mdacc_HNSCC-01-0300_CT-SIM-07-08-2007-
24105.0

61 th processing:___mdacc_HNSCC-01-0302_CT-SIM-07-08-2007-
13755.0

62 th processing:___mdacc_HNSCC-01-0303_CT-SIM-07-08-2007-
19443.0

63 th processing:___mdacc_HNSCC-01-0304_CT-SIM-07-08-2007-
23464.0

64 th processing:___mdacc_HNSCC-01-0305_CT-SIM-07-08-2007-
20915.0

65 th processing:___mdacc_HNSCC-01-0307_CT-SIM-07-08-2007-
18230.0

66 th processing:___mdacc_HNSCC-01-0308_CT-SIM-07-08-2007-
21906.0

67 th processing:___mdacc_HNSCC-01-0309_CT-SIM-07-08-2007-
18432.0

68 th processing:___mdacc_HNSCC-01-0310_CT-SIM-07-08-2007-
31525.0

69 th processing:___mdacc_HNSCC-01-0311_CT-SIM-07-08-2007-
16603.0

70 th processing:___mdacc_HNSCC-01-0313_CT-SIM-07-08-2007-
28765.0

71 th processing:___mdacc_HNSCC-01-0314_CT-SIM-07-08-2007-
20743.0

72 th processing:___mdacc_HNSCC-01-0315_CT-SIM-07-08-2007-
14053.0

73 th processing:___mdacc_HNSCC-01-0316_CT-SIM-07-08-2007-
20601.0

74 th processing:___mdacc_HNSCC-01-0318_CT-SIM-07-08-2007-
15277.0

75 th processing:___mdacc_HNSCC-01-0319_CT-SIM-07-08-2007-
23121.0

76 th processing:___mdacc_HNSCC-01-0320_CT-SIM-07-08-2007-
19113.0

77 th processing:___mdacc_HNSCC-01-0321_CT-SIM-07-08-2007-
17873.0

78 th processing:___mdacc_HNSCC-01-0323_CT-SIM-07-08-2007-
21006.0

79 th processing:___mdacc_HNSCC-01-0324_CT-SIM-07-08-2007-
12766.0

80 th processing:___mdacc_HNSCC-01-0325_CT-SIM-07-08-2007-
15326.0

81 th processing:___mdacc_HNSCC-01-0326_CT-SIM-07-08-2007-
28187.0

82 th processing:___mdacc_HNSCC-01-0328_CT-SIM-07-08-2007-
17697.0

83 th processing:___mdacc_HNSCC-01-0329_CT-SIM-08-10-2008-
14901.0

84 th processing:___mdacc_HNSCC-01-0330_CT-SIM-08-10-2008-
18915.0

85 th processing:___mdacc_HNSCC-01-0331_CT-SIM-08-10-2008-
18438.0

86 th processing:___mdacc_HNSCC-01-0333_CT-SIM-08-10-2008-
19293.0

87 th processing:___mdacc_HNSCC-01-0334_CT-SIM-08-10-2008-
14926.0

88 th processing:___mdacc_HNSCC-01-0335_CT-SIM-08-10-2008-
18618.0

89 th processing:___mdacc_HNSCC-01-0336_CT-SIM-08-10-2008-
19680.0

90 th processing:___mdacc_HNSCC-01-0338_CT-SIM-08-10-2008-
19739.0

91 th processing:___mdacc_HNSCC-01-0339_CT-SIM-08-10-2008-
15028.0

92 th processing:___mdacc_HNSCC-01-0340_CT-SIM-08-10-2008-
22742.0

93 th processing:___mdacc_HNSCC-01-0341_CT-SIM-08-10-2008-
18141.0

94 th processing:___mdacc_HNSCC-01-0342_CT-SIM-08-10-2008-
14343.0

95 th processing:___mdacc_HNSCC-01-0344_CT-SIM-08-10-2008-
20962.0

96 th processing:___mdacc_HNSCC-01-0345_CT-SIM-08-10-2008-
16180.0

97 th processing:___mdacc_HNSCC-01-0346_CT-SIM-08-10-2008-
19742.0

98 th processing:___mdacc_HNSCC-01-0347_CT-SIM-08-10-2008-
23668.0

99 th processing:___mdacc_HNSCC-01-0349_CT-SIM-08-10-2008-
21095.0

100 th processing:___mdacc_HNSCC-01-0350_CT-SIM-08-10-2008-
24761.0

101 th processing:___mdacc_HNSCC-01-0351_CT-SIM-08-10-2008-
14109.0

102 th processing:___mdacc_HNSCC-01-0352_CT-SIM-08-10-2008-
21281.0

103 th processing:___mdacc_HNSCC-01-0355_CT-SIM-08-10-2008-
20230.0

104 th processing:___mdacc_HNSCC-01-0356_CT-SIM-08-10-2008-
22246.0

105 th processing:___mdacc_HNSCC-01-0357_CT-SIM-08-10-2008-
15745.0

106 th processing:___mdacc_HNSCC-01-0358_CT-SIM-08-10-2008-
16882.0

107 th processing:___mdacc_HNSCC-01-0360_CT-SIM-08-10-2008-
18501.0

108 th processing:___mdacc_HNSCC-01-0361_CT-SIM-08-10-2008-
18944.0

109 th processing:___mdacc_HNSCC-01-0362_CT-SIM-08-10-2008-
16702.0

110 th processing:___mdacc_HNSCC-01-0363_CT-SIM-08-10-2008-
22188.0

111 th processing:___mdacc_HNSCC-01-0365_CT-SIM-08-10-2008-
18936.0

112 th processing:___mdacc_HNSCC-01-0366_CT-SIM-08-10-2008-
16104.0

113 th processing:___mdacc_HNSCC-01-0367_CT-SIM-08-10-2008-
18278.0

114 th processing:___mdacc_HNSCC-01-0368_CT-SIM-08-10-2008-
16200.0

115 th processing:___mdacc_HNSCC-01-0370_CT-SIM-08-10-2008-
18651.0

116 th processing:___mdacc_HNSCC-01-0371_CT-SIM-08-10-2008-
13633.0

117 th processing:___mdacc_HNSCC-01-0372_CT-SIM-08-10-2008-
24069.0

118 th processing:___mdacc_HNSCC-01-0373_CT-SIM-08-10-2008-
23377.0

119 th processing:___mdacc_HNSCC-01-0375_CT-SIM-08-10-2008-
22555.0

120 th processing:___mdacc_HNSCC-01-0376_CT-SIM-08-10-2008-
22648.0

121 th processing:___mdacc_HNSCC-01-0377_CT-SIM-08-10-2008-

21151.0

122 th processing:___mdacc_HNSCC-01-0378_CT-SIM-08-10-2008-
15499.0

123 th processing:___mdacc_HNSCC-01-0380_CT-SIM-08-10-2008-
15997.0

124 th processing:___mdacc_HNSCC-01-0381_CT-SIM-08-10-2008-
23179.0

125 th processing:___mdacc_HNSCC-01-0382_CT-SIM-08-10-2008-
15717.0

126 th processing:___mdacc_HNSCC-01-0383_CT-SIM-08-10-2008-
18634.0

127 th processing:___mdacc_HNSCC-01-0385_CT-SIM-08-10-2008-
20751.0

128 th processing:___mdacc_HNSCC-01-0386_CT-SIM-08-10-2008-
13405.0

129 th processing:___mdacc_HNSCC-01-0387_CT-SIM-08-10-2008-
20947.0

130 th processing:___mdacc_HNSCC-01-0388_CT-SIM-08-10-2008-
17720.0

131 th processing:___mdacc_HNSCC-01-0390_CT-SIM-08-10-2008-
21074.0

132 th processing:___mdacc_HNSCC-01-0391_CT-SIM-08-10-2008-
18366.0

133 th processing:___mdacc_HNSCC-01-0392_CT-SIM-08-10-2008-
22354.0

134 th processing:___mdacc_HNSCC-01-0393_CT-SIM-08-10-2008-
18446.0

135 th processing:___mdacc_HNSCC-01-0395_CT-SIM-08-10-2008-
22223.0

136 th processing:___mdacc_HNSCC-01-0396_CT-SIM-09-13-2009-
21422.0

137 th processing:___mdacc_HNSCC-01-0397_CT-SIM-09-13-2009-
9615.0

138 th processing:___mdacc_HNSCC-01-0398_CT-SIM-09-13-2009-
17661.0

139 th processing:___mdacc_HNSCC-01-0400_CT-SIM-09-13-2009-
17631.0

140 th processing:___mdacc_HNSCC-01-0401_CT-SIM-09-13-2009-
24577.0

141 th processing:___mdacc_HNSCC-01-0402_CT-SIM-11-13-2011-
12452.0

142 th processing:___mdacc_HNSCC-01-0403_CT-SIM-09-13-2009-
19007.0

143 th processing:___mdacc_HNSCC-01-0405_CT-SIM-09-13-2009-
18108.0

144 th processing:___mdacc_HNSCC-01-0406_CT-SIM-09-13-2009-
16261.0

145 th processing:___mdacc_HNSCC-01-0407_CT-SIM-09-13-2009-
20156.0

146 th processing:___mdacc_HNSCC-01-0408_CT-SIM-09-13-2009-
18088.0

147 th processing:___mdacc_HNSCC-01-0410_CT-SIM-09-13-2009-
20666.0

148 th processing:___mdacc_HNSCC-01-0411_CT-SIM-09-13-2009-
17390.0

149 th processing:___mdacc_HNSCC-01-0412_CT-SIM-09-13-2009-
19754.0

150 th processing:___mdacc_HNSCC-01-0413_CT-SIM-09-13-2009-
22934.0

151 th processing:___mdacc_HNSCC-01-0415_CT-SIM-09-13-2009-
17292.0

152 th processing:___mdacc_HNSCC-01-0416_CT-SIM-09-13-2009-
18790.0

153 th processing:___mdacc_HNSCC-01-0417_CT-SIM-09-13-2009-
29083.0

154 th processing:___mdacc_HNSCC-01-0418_CT-SIM-09-13-2009-
21171.0

155 th processing:___mdacc_HNSCC-01-0420_CT-SIM-09-13-2009-
22132.0

156 th processing:___mdacc_HNSCC-01-0421_CT-SIM-09-13-2009-
23991.0

157 th processing:___mdacc_HNSCC-01-0422_CT-SIM-09-13-2009-
22272.0

158 th processing:___mdacc_HNSCC-01-0423_CT-SIM-09-13-2009-
26812.0

159 th processing:___mdacc_HNSCC-01-0425_CT-SIM-09-13-2009-
17396.0

160 th processing:___mdacc_HNSCC-01-0426_CT-SIM-09-13-2009-
16848.0

161 th processing:___mdacc_HNSCC-01-0427_CT-SIM-09-13-2009-
27831.0

162 th processing:___mdacc_HNSCC-01-0428_CT-SIM-09-13-2009-
22079.0

163 th processing:___mdacc_HNSCC-01-0430_CT-SIM-09-13-2009-
21161.0

164 th processing:___mdacc_HNSCC-01-0431_CT-SIM-09-13-2009-
21200.0

165 th processing:___mdacc_HNSCC-01-0432_CT-SIM-09-13-2009-
22815.0

166 th processing:___mdacc_HNSCC-01-0433_CT-SIM-09-13-2009-
20288.0

167 th processing:___mdacc_HNSCC-01-0436_CT-SIM-09-13-2009-
15230.0

168 th processing:___mdacc_HNSCC-01-0437_CT-SIM-09-13-2009-
26771.0

169 th processing:___mdacc_HNSCC-01-0438_CT-SIM-09-13-2009-
18740.0

170 th processing:___mdacc_HNSCC-01-0439_CT-SIM-09-13-2009-
17982.0

171 th processing:___mdacc_HNSCC-01-0441_CT-SIM-09-13-2009-
18269.0

172 th processing:___mdacc_HNSCC-01-0442_CT-SIM-09-13-2009-
10835.0

173 th processing:___mdacc_HNSCC-01-0443_CT-SIM-08-10-2008-
20085.0

174 th processing:___mdacc_HNSCC-01-0444_CT-SIM-09-13-2009-
24068.0

175 th processing:___mdacc_HNSCC-01-0446_CT-SIM-09-13-2009-
16760.0

176 th processing:___mdacc_HNSCC-01-0447_CT-SIM-09-13-2009-
20090.0

177 th processing:___mdacc_HNSCC-01-0448_CT-SIM-09-13-2009-
20979.0

178 th processing:___mdacc_HNSCC-01-0449_CT-SIM-09-13-2009-
14870.0

179 th processing:___mdacc_HNSCC-01-0451_CT-SIM-09-13-2009-
23686.0

180 th processing:___mdacc_HNSCC-01-0452_CT-SIM-09-13-2009-
20735.0

181 th processing:___mdacc_HNSCC-01-0453_CT-SIM-09-13-2009-
11727.0

182 th processing:___mdacc_HNSCC-01-0454_CT-SIM-09-13-2009-
21356.0

183 th processing:___mdacc_HNSCC-01-0456_CT-SIM-09-13-2009-
20267.0

184 th processing:___mdacc_HNSCC-01-0457_CT-SIM-09-13-2009-
12021.0

185 th processing:___mdacc_HNSCC-01-0459_CT-SIM-09-13-2009-
23291.0

186 th processing:___mdacc_HNSCC-01-0460_CT-SIM-09-13-2009-
11681.0

187 th processing:___mdacc_HNSCC-01-0462_CT-SIM-09-13-2009-
23550.0

188 th processing:___mdacc_HNSCC-01-0463_CT-SIM-09-13-2009-
11559.0

189 th processing:___mdacc_HNSCC-01-0465_CT-SIM-09-13-2009-
21218.0

190 th processing:___mdacc_HNSCC-01-0466_CT-SIM-09-13-2009-
17292.0

191 th processing:___mdacc_HNSCC-01-0468_CT-SIM-09-13-2009-
20780.0

192 th processing:___mdacc_HNSCC-01-0469_CT-SIM-09-13-2009-
15200.0

193 th processing:___mdacc_HNSCC-01-0470_CT-SIM-09-13-2009-
16066.0

194 th processing:___mdacc_HNSCC-01-0471_CT-SIM-09-13-2009-
19735.0

195 th processing:___mdacc_HNSCC-01-0473_CT-SIM-09-13-2009-
17768.0

196 th processing:___mdacc_HNSCC-01-0474_CT-SIM-09-13-2009-
30457.0

197 th processing:___mdacc_HNSCC-01-0475_CT-SIM-10-10-2010-
17746.0

198 th processing:___mdacc_HNSCC-01-0476_CT-SIM-10-10-2010-
13881.0

199 th processing:___mdacc_HNSCC-01-0478_CT-SIM-10-10-2010-
12515.0

200 th processing:___mdacc_HNSCC-01-0479_CT-SIM-10-10-2010-
22143.0

201 th processing:___mdacc_HNSCC-01-0480_CT-SIM-10-10-2010-
17346.0

202 th processing:___mdacc_HNSCC-01-0481_CT-SIM-10-10-2010-
23618.0

203 th processing:___mdacc_HNSCC-01-0483_CT-SIM-10-10-2010-
16043.0

204 th processing:___mdacc_HNSCC-01-0484_CT-SIM-10-10-2010-
11859.0

205 th processing:___mdacc_HNSCC-01-0485_CT-SIM-10-10-2010-
22202.0

206 th processing:___mdacc_HNSCC-01-0486_CT-SIM-10-10-2010-
25880.0

207 th processing:___mdacc_HNSCC-01-0488_CT-SIM-10-10-2010-
13974.0

208 th processing:___mdacc_HNSCC-01-0489_CT-SIM-10-10-2010-
17762.0

209 th processing:___mdacc_HNSCC-01-0491_CT-SIM-10-10-2010-
17749.0

210 th processing:___mdacc_HNSCC-01-0492_CT-SIM-10-10-2010-
21325.0

211 th processing:___mdacc_HNSCC-01-0494_CT-SIM-10-10-2010-
22113.0

212 th processing:___mdacc_HNSCC-01-0495_CT-SIM-10-10-2010-
15559.0

213 th processing:___mdacc_HNSCC-01-0496_CT-SIM-10-10-2010-
11134.0

214 th processing:___mdacc_HNSCC-01-0497_CT-SIM-10-10-2010-
25501.0

215 th processing:___mdacc_HNSCC-01-0499_CT-SIM-10-10-2010-
18429.0

216 th processing:___mdacc_HNSCC-01-0500_CT-SIM-10-10-2010-
17307.0

217 th processing:___mdacc_HNSCC-01-0502_CT-SIM-10-10-2010-
21208.0

218 th processing:___mdacc_HNSCC-01-0503_CT-SIM-10-10-2010-
19969.0

219 th processing:___mdacc_HNSCC-01-0505_CT-SIM-10-10-2010-
17850.0

220 th processing:___mdacc_HNSCC-01-0506_CT-SIM-10-10-2010-
30160.0

221 th processing:___mdacc_HNSCC-01-0507_CT-SIM-10-10-2010-
17825.0

222 th processing:___mdacc_HNSCC-01-0508_CT-SIM-10-10-2010-
16750.0

223 th processing:___mdacc_HNSCC-01-0510_CT-SIM-10-10-2010-
19485.0

224 th processing:___mdacc_HNSCC-01-0511_CT-SIM-10-10-2010-
21974.0

225 th processing:___mdacc_HNSCC-01-0512_CT-SIM-10-10-2010-
20925.0

226 th processing:___mdacc_HNSCC-01-0513_CT-SIM-10-10-2010-
14614.0

227 th processing:___mdacc_HNSCC-01-0516_CT-SIM-10-10-2010-
22588.0

228 th processing:___mdacc_HNSCC-01-0517_CT-SIM-10-10-2010-
20011.0

229 th processing:___mdacc_HNSCC-01-0518_CT-SIM-10-10-2010-
9828.0

230 th processing:___mdacc_HNSCC-01-0519_CT-SIM-10-10-2010-
21788.0

231 th processing:___mdacc_HNSCC-01-0522_CT-SIM-10-10-2010-
18777.0

232 th processing:___mdacc_HNSCC-01-0523_CT-SIM-10-10-2010-
21092.0

233 th processing:___mdacc_HNSCC-01-0524_CT-SIM-10-10-2010-
15757.0

234 th processing:___mdacc_HNSCC-01-0525_CT-SIM-10-10-2010-
11057.0

235 th processing:___mdacc_HNSCC-01-0527_CT-SIM-10-10-2010-
17643.0

236 th processing:___mdacc_HNSCC-01-0528_CT-SIM-10-10-2010-
11421.0

237 th processing:___mdacc_HNSCC-01-0529_CT-SIM-10-10-2010-
19387.0

238 th processing:___mdacc_HNSCC-01-0530_CT-SIM-10-10-2010-
28919.0

239 th processing:___mdacc_HNSCC-01-0532_CT-SIM-10-10-2010-
17652.0

240 th processing:___mdacc_HNSCC-01-0534_CT-SIM-10-10-2010-

20736.0

241 th processing:___mdacc_HNSCC-01-0535_CT-SIM-10-10-2010-
13584.0

242 th processing:___mdacc_HNSCC-01-0536_CT-SIM-10-10-2010-
12385.0

243 th processing:___mdacc_HNSCC-01-0538_CT-SIM-10-10-2010-
19519.0

244 th processing:___mdacc_HNSCC-01-0539_CT-SIM-10-10-2010-
17992.0

245 th processing:___mdacc_HNSCC-01-0540_CT-SIM-10-10-2010-
11791.0

246 th processing:___mdacc_HNSCC-01-0541_CT-SIM-10-10-2010-
21882.0

247 th processing:___mdacc_HNSCC-01-0543_CT-SIM-11-13-2011-
19743.0

In [5]:
images = val_images
labels = val_masks
for i in range(len(images)):
    if (images[i].split('/')[-1][:20]==labels[i].split('/')[-1][:20] ):
        print(i+1,'th processing:   '+images[i].split('/')[-1][:20])
        image_sitk = sitk.ReadImage(images[i])
        label_sitk = sitk.ReadImage(labels[i])
        
        seg_slice = val_slices[i]
        image_array  = sitk.GetArrayFromImage(image_sitk)[seg_slice,:,:].reshape(1,512,512,1)
        label_array  = sitk.GetArrayFromImage(label_sitk )[seg_slice,:,:].reshape(1,512,512,1)
        print(np.sum(label_array))
        val_images_array[i,:,:,:] = image_array
        val_masks_array[i,:,:,:] = label_array
        print()
 
    val_masks_array=val_masks_array.astype(np.uint8)
np.save('../data/train/train_segmentation/val_images.npy',val_images_array)
np.save('../data/train/train_segmentation/val_masks.npy',val_masks_array)

1 th processing:   mdacc_HNSCC-01-0216_
19560.0

2 th processing:   mdacc_HNSCC-01-0221_
16956.0

3 th processing:   mdacc_HNSCC-01-0231_
21771.0

4 th processing:   mdacc_HNSCC-01-0236_
19808.0

5 th processing:   mdacc_HNSCC-01-0241_
23254.0

6 th processing:   mdacc_HNSCC-01-0246_
20549.0

7 th processing:   mdacc_HNSCC-01-0251_
36684.0

8 th processing:   mdacc_HNSCC-01-0256_
18848.0

9 th processing:   mdacc_HNSCC-01-0261_
21176.0

10 th processing:   mdacc_HNSCC-01-0266_
14545.0

11 th processing:   mdacc_HNSCC-01-0272_
18370.0

12 th processing:   mdacc_HNSCC-01-0277_
20085.0

13 th processing:   mdacc_HNSCC-01-0284_
16501.0

14 th processing:   mdacc_HNSCC-01-0289_
18646.0

15 th processing:   mdacc_HNSCC-01-0294_
14972.0

16 th processing:   mdacc_HNSCC-01-0301_
16007.0

17 th processing:   mdacc_HNSCC-01-0306_
20635.0

18 th processing:   mdacc_HNSCC-01-0312_
18430.0

19 th processing:   mdacc_HNSCC-01-0317_
20419.0

20 th processing:   mdacc_HNSCC-01-0322_
18921.0

21 th processing:   mdacc_HNSCC-01-0327_
27879.0

22 th processing:   mdacc_HNSCC-01-0332_
17203.0

23 th processing:   mdacc_HNSCC-01-0337_
20294.0

24 th processing:   mdacc_HNSCC-01-0343_
20947.0

25 th processing:   mdacc_HNSCC-01-0348_
21848.0

26 th processing:   mdacc_HNSCC-01-0354_
18437.0

27 th processing:   mdacc_HNSCC-01-0359_
21220.0

28 th processing:   mdacc_HNSCC-01-0364_
20833.0

29 th processing:   mdacc_HNSCC-01-0369_
22184.0

30 th processing:   mdacc_HNSCC-01-0374_
20033.0

31 th processing:   mdacc_HNSCC-01-0379_
17200.0

32 th processing:   mdacc_HNSCC-01-0384_
12373.0

33 th processing:   mdacc_HNSCC-01-0389_
19305.0

34 th processing:   mdacc_HNSCC-01-0394_
18080.0

35 th processing:   mdacc_HNSCC-01-0399_
10576.0

36 th processing:   mdacc_HNSCC-01-0404_
27079.0

37 th processing:   mdacc_HNSCC-01-0409_
12663.0

38 th processing:   mdacc_HNSCC-01-0414_
24698.0

39 th processing:   mdacc_HNSCC-01-0419_
22857.0

40 th processing:   mdacc_HNSCC-01-0424_
21341.0

41 th processing:   mdacc_HNSCC-01-0429_
16841.0

42 th processing:   mdacc_HNSCC-01-0434_
22584.0

43 th processing:   mdacc_HNSCC-01-0440_
17494.0

44 th processing:   mdacc_HNSCC-01-0445_
17511.0

45 th processing:   mdacc_HNSCC-01-0450_
20956.0

46 th processing:   mdacc_HNSCC-01-0455_
19824.0

47 th processing:   mdacc_HNSCC-01-0461_
21338.0

48 th processing:   mdacc_HNSCC-01-0467_
19775.0

49 th processing:   mdacc_HNSCC-01-0472_
14096.0

50 th processing:   mdacc_HNSCC-01-0477_
19660.0

51 th processing:   mdacc_HNSCC-01-0482_
25784.0

52 th processing:   mdacc_HNSCC-01-0487_
15290.0

53 th processing:   mdacc_HNSCC-01-0493_
19115.0

54 th processing:   mdacc_HNSCC-01-0498_
40745.0

55 th processing:   mdacc_HNSCC-01-0504_
18528.0

56 th processing:   mdacc_HNSCC-01-0509_
23246.0

57 th processing:   mdacc_HNSCC-01-0514_
20888.0

58 th processing:   mdacc_HNSCC-01-0521_
17759.0

59 th processing:   mdacc_HNSCC-01-0526_
22819.0

60 th processing:   mdacc_HNSCC-01-0531_
18604.0

61 th processing:   mdacc_HNSCC-01-0537_
20701.0

62 th processing:   mdacc_HNSCC-01-0542_
21247.0